/* =====================================================================
   language.js — Legends Indev Modüler Dil Mimarisi
   ---------------------------------------------------------------------
   Bu dosya oyunun tüm arayüz metinlerini (menüler, F3 debug ekranı,
   dünya oluşturma ekranı, Hardcore ölüm ekranı, ayarlar vb.) içeren
   sözlük yapısını barındırır. game-40.html dosyasından ÖNCE
   game-40.html içine harici script olarak dahil edilmelidir (script tag,
   src="language.js" ile, head içinde en üstte).

   Desteklenen diller: en (varsayılan), tr, de, fr, es, ru, pt
   Varsayılan dil: EN (İngilizce). Kullanıcı dil değiştirdiğinde tercih
   localStorage'a (legends_lang anahtarı) kaydedilir ve oyun yeniden
   açıldığında otomatik olarak yüklenir.
   ===================================================================== */
(function(global){
  "use strict";

  var STORAGE_KEY = "legends_lang";
  var DEFAULT_LANG = "en";
  var SUPPORTED = ["en","tr","de","fr","es","ru","pt"];

  // ── Tam sözlük verisi (tüm diller, 272 anahtar/dil) ────────────────
  var LANG_DATA = {
  "en": {
    "title": "LEGENDS INDEV",
    "singleplayer": "SINGLE PLAYER",
    "multiplayer": "MULTIPLAYER",
    "settings": "SETTINGS",
    "deviceTitle": "SELECT DEVICE",
    "pcBtn": "COMPUTER",
    "mobileBtn": "MOBILE",
    "worldTitle": "SELECT WORLD",
    "wInfTitle": "NORMAL WORLD",
    "wInfDesc": "Perlin Noise terrain",
    "wSmTitle": "SMALL WORLD",
    "wSmDesc": "Lightweight and fast",
    "wFlatTitle": "FLAT WORLD",
    "wFlatDesc": "Completely flat terrain",
    "back": "← BACK",
    "errTitle": "Graphics Engine Error!",
    "errDesc": "Please check your internet connection.",
    "resume": "RESUME",
    "quit": "QUIT",
    "pauseTitle": "GAME MENU",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "JUMP",
    "mpTitle": "MULTIPLAYER",
    "mpJoin": "JOIN",
    "mpHost": "HOST",
    "settingsTitle": "SETTINGS",
    "joinTitle": "JOIN ROOM",
    "joinNamePh": "Your player name",
    "joinCodePh": "4-LETTER CODE",
    "joinBtn": "JOIN",
    "hostTitle": "HOST ROOM",
    "hostNamePh": "Your player name",
    "hostStart": "START ROOM",
    "codeLabel": "ROOM CODE",
    "wmcInf": "NORMAL",
    "wmcFlat": "FLAT",
    "wmcSm": "SMALL",
    "gmcSurv": "SURVIVAL",
    "gmcCrea": "CREATIVE",
    "gmcAdv": "ADVENTURE",
    "chatHint": "⌨  Enter → Chat",
    "chatPh": "Type a message...",
    "sysJoin": " joined",
    "sysLeft": " left",
    "sysDisc": "Connection lost",
    "sysSpawnSet": "✅ World spawn point updated!",
    "sysSpawnSetUsage": "Usage: /setworldspawn (must be host)",
    "srvUsageSetblock": "Usage: /setblock <x> <y> <z> <block>",
    "srvSetblockSuccess": "✅ Block placed at: ",
    "srvUsageFill": "Usage: /fill <x1> <y1> <z1> <x2> <y2> <z2> <block>",
    "srvFillSuccess": "✅ Region filled, block count: ",
    "srvFillTooLarge": "⚠️ Too many blocks (limit exceeded): ",
    "crosshairModeLabel": "🎯 Crosshair Mode",
    "crosshairModeSublabel": "(place block at center)",
    "srvSpawnCodeMissing": "⚠️ Room code not found, could not reach server.",
    "srvSpawnNoConnection": "⚠️ Not connected to server.",
    "srvSpawnFailed": "⚠️ Could not set spawn point: ",
    "sysPlayerSaved": "💾 Position and inventory saved.",
    "modeCreative": "Creative Mode",
    "modeSurvival": "Survival Mode",
    "modeAdventure": "Adventure Mode",
    "rdLabel": "Render Distance",
    "rdPcLabel": "Render Distance",
    "rdMLabel": "Render Distance",
    "spSurv": "SURVIVAL",
    "spCrea": "CREATIVE",
    "spAdv": "ADVENTURE",
    "crouchBtn": "CROUCH",
    "worldSectionLabel": "WORLD",
    "gameModeSectionLabel": "GAME MODE",
    "cheatsLabel": "CHEATS",
    "cheatOff": "OFF",
    "cheatOn": "ON",
    "deathTitle": "You Died!",
    "respawnBtn": "Respawn",
    "pauseSettings": "SETTINGS",
    "mpBrowse": "BROWSE",
    "mpLoad": "LOAD",
    "mpCreate": "CREATE",
    "mpServerList": "SERVER LIST",
    "invTitle": "INVENTORY",
    "invBlocks": "BLOCKS",
    "invHint": "HOTBAR – SELECT A BLOCK, THEN CLICK A SLOT TO ASSIGN",
    "invClose": "[E] close",
    "bkNames": [
      "Planks",
      "Grass",
      "Dirt",
      "Stone",
      "Log",
      "Cobblestone",
      "Glass",
      "Leaves",
      "Sand",
      "Water",
      "Bedrock",
      "Lava",
      "Obsidian",
      "Andesite",
      "Granite",
      "Diorite",
      "Gravel"
    ],
    "settingsPcBtn": "PC SETTINGS",
    "settingsMobileBtn": "MOBILE SETTINGS",
    "pcSettingsTitle": "PC SETTINGS",
    "mobileSettingsTitle": "MOBILE SETTINGS",
    "sensLabel": "Sensitivity",
    "fovLabel": "Field of View (FOV)",
    "keybindsTitle": "KEY BINDINGS",
    "kbForward": "Forward",
    "kbBack": "Back",
    "kbLeft": "Left",
    "kbRight": "Right",
    "kbJump": "Jump",
    "kbSlot": "Select Slot",
    "kbBreak": "Break Block",
    "kbPlace": "Place Block",
    "kbChat": "Chat",
    "kbPause": "Pause",
    "srvPrefix": "[Server]: ",
    "srvNoCheat": "[Server]: Cheats are disabled!",
    "srvNoPerms": "[Server]: You don't have permission!",
    "srvHostOnly": "[Server]: Host only!",
    "srvUsageMode": "Usage: /mode c, /mode s or /mode a",
    "srvUsageOp": "Usage: /op <name>",
    "srvUsageUnop": "Usage: /unop <name>",
    "srvUsageKick": "Usage: /kick <name>",
    "srvUsageBan": "Usage: /ban <name>",
    "srvNoPlayer": "[Server]: Player not found: ",
    "srvNoCantKickOp": "[Server]: Cannot kick operators!",
    "srvNoCantBanOp": "[Server]: Cannot ban operators!",
    "srvUnknownCmd": "Unknown command: /",
    "srvUnknownEntity": "Unknown entity: ",
    "srvUsageSummon": "Usage: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Could not spawn entity (chunk not loaded).",
    "srvSummonSuccess": "Spawned %e at (%x, %y, %z)",
    "srvFriendUsage": "Usage: /friend <playerName>",
    "srvFriendSent": "Friend request sent!",
    "srvFriendGuest": "Cannot send friend request to unregistered players!",
    "srvFriendSelf": "You cannot send a friend request to yourself!",
    "srvModeChanged": "Mode: ",
    "srvOpGranted": " is now operator!",
    "srvOpRevoked": " is no longer operator.",
    "srvKicked": " was kicked.",
    "srvBanned": " was banned.",
    "srvUnbanned": " was unbanned.",
    "srvKickedBy": " kicked you.",
    "srvOpBecame": " became operator",
    "srvOpLost": " is no longer operator",
    "srvKickedNotice": "You were removed from the server: ",
    "banScreenTitle": "You have been banned from this server!",
    "kickScreenTitle": "You have been kicked from the server!",
    "banByText": " banned you!",
    "kickByText": " kicked you!",
    "backToMenuBtn": "Back to Main Menu",
    "rateLimitMsg": "You are sending messages too fast!",
    "deathMessages": {
      "fall": "High fall",
      "suffocation": "Suffocation",
      "void": "Void",
      "pvp": "PvP",
      "lava": "Lava",
      "fire": "Fire",
      "unknown": "Unknown"
    },
    "deathChat": {
      "pvp": "%V% was killed by %A%",
      "suffocation": "%V% suffocated in a wall",
      "void": "%V% fell out of the world",
      "fall": "%V% fell from a high place",
      "lava": "%V% burned to death in lava",
      "fire": "%V% burned to death"
    },
    "killDeathMsg": "Player died",
    "killAllMsg": "[Server]: All players were killed",
    "srvUsageKillCmd": "Usage: /kill | /kill @p | /kill @a | /kill <name>",
    "srvKillNoPlayer": "[Server]: Player not found: ",
    "srvCheatsOn": "[Server]: Cheats enabled!",
    "srvCheatsOff": "[Server]: Cheats disabled!",
    "srvUsageCheats": "Usage: /cheats on or /cheats off",
    "srvCheatsHostOnly": "[Server]: Only the host can change cheats!",
    "srvMpOnlyCmd": "[Server]: This command can only be used in multiplayer",
    "srvCheatsSpOnly": "[Server]: Cheats can be toggled from the menu!",
    "srvShoutNoPerm": "This command is for Twitch rank and above",
    "srvUsageShout": "Usage: /shout <message>",
    "camFirstPerson": "🎥 First Person",
    "camThirdBack": "🎥 Third Person (Back)",
    "camThirdFront": "🎥 Third Person (Front)",
    "skinTitle": "SKIN SETTINGS",
    "skinPreview": "PREVIEW",
    "skinUploader": "SKIN UPLOADER",
    "skinUploadHint": "📁 Upload Minecraft skin PNG",
    "skinUploadSize": "64×64, 64×32 or 128×128 pixels",
    "skinChoose": "📂 CHOOSE FILE",
    "skinReset": "🔄 RESET TO STEVE",
    "skinMenuBtn": "🎨 CUSTOM SKIN",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Your skin is visible to other players in multiplayer.",
    "skinLoaded": "✅ Skin loaded!",
    "skinError": "❌ Error: Must be a 64×64, 64×32 or 128×128 PNG.",
    "skinGuestWarning": "🔒 An account is required to upload a custom skin.",
    "skinGuestHint": "Log in to the site if you have an account.",
    "heightLimitMsg": "⛔ Height limit for building has been reached! (250 Blocks)",
    "worldBorderMsg": "⛔ You have reached the world border!",
    "giveUsage": "Usage: /give <target> <block>",
    "giveUnknownBlock": "Unknown block: ",
    "giveSuccess": "Given: ",
    "giveNoTarget": "Target not found: ",
    "helpTitle": "─── COMMANDS ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Change mode (creative/survival/adventure/spectator)",
      "/give <@p|@a|name> <block>  →  Give a block",
      "/kill [@p|@a|name]  →  Kill player",
      "/op <name>  →  Grant operator",
      "/unop <name>  →  Revoke operator",
      "/kick <name>  →  Kick player",
      "/ban <name>  →  Ban player",
      "/unban <name>  →  Unban player",
      "/setworldspawn  →  Set world spawn point",
      "/setblock <x> <y> <z> <block>  →  Place a block at position",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <block>  →  Fill region with block",
      "/summon <sheep|cow|pig> [x y z]  →  Spawn an entity",
      "/friend <name>  →  Friend request",
      "/shout <msg>  →  Global message",
      "/help  →  Show this menu"
    ],
    "tmTitle": "TESTING PHASE",
    "tmDesc": "You are not logged in. In normal conditions, this action requires an account.<br><br>Since the game is in <strong style=\"color:#ffc84a\">Development / Testing</strong> phase, you can continue without an account. However this version <strong style=\"color:#ff7a7a\">may contain bugs and missing features</strong>, server data will be sent as a guest.",
    "tmContinue": "CONTINUE ANYWAY",
    "tmCancel": "CANCEL",
    "guestCreateTitle": "An account is required to create a server.",
    "guestCreateHint": "Log in to the site to use this feature.",
    "guestLoadMsg": "🔒 An account is required to load a world.",
    "guestCreateMsg": "🔒 An account is required to create a server. Please log in.",
    "slTitle": "SERVER LIST",
    "slSavedWorld": "SELECT SAVED WORLD",
    "slNoBrowser": "No saved worlds found in your browser.",
    "slServerSettings": "SERVER SETTINGS",
    "slLoadHost": "LOAD & HOST",
    "slWorldLoading": "Loading world...",
    "slWorldReadError": "⚠ Could not read world data.",
    "slServerError": "⚠ Server error: ",
    "slSearchPh": "Search server...",
    "slConnecting": "Loading servers...",
    "slNoResponse": "⚠ No response from server.",
    "slNoServers": "No active servers found.",
    "slCreateServer": "⚙️ CREATE SERVER",
    "msTitle": "⚙ MANAGE SERVER",
    "msTabPlayers": "👥 PLAYERS",
    "msTabAdmins": "🛡 ADMINS & BANS",
    "msTabServer": "⚙ SERVER",
    "msBtnManage": "🛡 MANAGE SERVER",
    "msLblAdmins": "ADMINS",
    "msLblBanned": "BANNED",
    "msLblAccess": "Access",
    "msLblPvp": "PvP",
    "msLblCheats": "Cheats",
    "msOptPublic": "🌐 Public",
    "msOptRegistered": "🔑 Registered Only",
    "msOptPrivate": "🔒 Private",
    "msBtnPromote": "Promote",
    "msBtnDemote": "Demote",
    "msBtnKick": "Kick",
    "msBtnBan": "Ban",
    "msBtnUnban": "Unban",
    "msBtnShutdown": "🛑 SHUTDOWN SERVER",
    "msBtnClose": "← CLOSE",
    "msNoPlayers": "No players in server.",
    "msNoAdmins": "No admins.",
    "msNoBanned": "No banned players.",
    "msPvpOn": "ON",
    "msPvpOff": "OFF",
    "msCheatsOn": "ON",
    "msCheatsOff": "OFF",
    "hcModLabel": "HARDCORE MODE",
    "hcOn": "ON",
    "hcOff": "OFF",
    "hcWatchWorld": "Watch World",
    "hcMainMenu": "Return to Main Menu",
    "hcBlockedGeneric": "⛔ Commands are blocked in Hardcore mode.",
    "hcBlockedSpectator": "⛔ Blocked in Hardcore.",
    "specModeSet": "Game mode set to Spectator.",
    "hcWorldEnded": "💀 This Hardcore world has ended. You can only spectate.",
    "spStateRestored": "💾 World state restored.",
    "spDeadTag": "☠ DEAD",
    "spDeadTooltip": "Opens in Spectator mode",
    "myWorldsTitle": "MY WORLDS",
    "newWorldBtn": "➕ CREATE NEW WORLD",
    "noWorldsYet": "No saved worlds yet.",
    "noWorldsHint": "Create or play a new world.",
    "editWorldName": "WORLD NAME",
    "editWorldNamePh": "World Name...",
    "editWorldType": "WORLD TYPE",
    "editGameMode": "GAME MODE",
    "editCheats": "CHEATS",
    "saveBtn": "💾 SAVE",
    "cancelBtn": "✖ CANCEL",
    "wtNormal": "NORMAL",
    "wtFlat": "FLAT",
    "wtSmall": "SMALL",
    "gmSurvival": "SURVIVAL",
    "gmCreative": "CREATIVE",
    "gmAdventure": "ADVENTURE",
    "chOff": "OFF",
    "chOn": "ON",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Block",
    "f3Chunk": "Chunk",
    "f3Facing": "Facing",
    "f3Pitch": "Pitch",
    "f3Biome": "Biome",
    "f3Targeted": "Targeted",
    "f3World": "World",
    "f3Seed": "Seed",
    "f3Mode": "Mode",
    "f3Flying": "Flying",
    "f3Grounded": "Grounded",
    "f3Chunks": "Chunks",
    "controlsTabLabel": "Controls",
    "languageTabLabel": "Language"
  },
  "tr": {
    "title": "LEGENDS INDEV",
    "singleplayer": "TEK OYUNCU",
    "multiplayer": "ÇOK OYUNCU",
    "settings": "AYARLAR",
    "deviceTitle": "CİHAZ SEÇİMİ",
    "pcBtn": "BİLGİSAYAR",
    "mobileBtn": "MOBİL",
    "worldTitle": "DÜNYA SEÇİMİ",
    "wInfTitle": "NORMAL DÜNYA",
    "wInfDesc": "Perlin Noise arazi, dinamik chunk",
    "wSmTitle": "KÜÇÜK DÜNYA",
    "wSmDesc": "Hafif ve hızlı",
    "wFlatTitle": "DÜZ DÜNYA",
    "wFlatDesc": "Tamamen düz zemin",
    "back": "← GERİ",
    "errTitle": "Grafik Motoru Hatası!",
    "errDesc": "İnternet bağlantınızı kontrol edin.",
    "resume": "DEVAM ET",
    "quit": "ÇIK",
    "pauseTitle": "OYUN MENÜSÜ",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "ZIPLA",
    "mpTitle": "ÇOK OYUNCULU",
    "mpJoin": "KATIL",
    "mpHost": "ODA KUR",
    "settingsTitle": "AYARLAR",
    "joinTitle": "ODAYA KATIL",
    "joinNamePh": "Oyuncu adınız",
    "joinCodePh": "4 HARFLİ ŞİFRE",
    "joinBtn": "KATIL",
    "hostTitle": "ODA KUR",
    "hostNamePh": "Oyuncu adınız",
    "hostStart": "ODAYI BAŞLAT",
    "codeLabel": "ODA ŞİFRESİ",
    "wmcInf": "NORMAL",
    "wmcFlat": "DÜZ",
    "wmcSm": "KÜÇÜK",
    "gmcSurv": "HAY. KALMA",
    "gmcCrea": "YARATICI",
    "gmcAdv": "MACERA",
    "chatHint": "⌨  Enter → Sohbet",
    "chatPh": "Mesajınızı yazın...",
    "sysJoin": " odaya katıldı",
    "sysLeft": " ayrıldı",
    "sysDisc": "Bağlantı kesildi",
    "sysSpawnSet": "✅ Dünya doğum noktası güncellendi!",
    "sysSpawnSetUsage": "Kullanım: /setworldspawn (host olman gerekir)",
    "srvUsageSetblock": "Kullanım: /setblock <x> <y> <z> <blok>",
    "srvSetblockSuccess": "✅ Blok konuldu: ",
    "srvUsageFill": "Kullanım: /fill <x1> <y1> <z1> <x2> <y2> <z2> <blok>",
    "srvFillSuccess": "✅ Alan dolduruldu, blok sayısı: ",
    "srvFillTooLarge": "⚠️ Çok fazla blok (sınır aşıldı): ",
    "crosshairModeLabel": "🎯 Crosshair Modu",
    "crosshairModeSublabel": "(merkeze blok koy)",
    "srvSpawnCodeMissing": "⚠️ Oda kodu bulunamadı, sunucuya iletilemedi.",
    "srvSpawnNoConnection": "⚠️ Sunucuya bağlı değilsiniz.",
    "srvSpawnFailed": "⚠️ Doğum noktası ayarlanamadı: ",
    "sysPlayerSaved": "💾 Konum ve envanter kaydedildi.",
    "modeCreative": "Yaratıcı Mod",
    "modeSurvival": "Hayatta Kalma",
    "modeAdventure": "Macera Modu",
    "rdLabel": "Görüş Mesafesi",
    "rdPcLabel": "Görüş Mesafesi",
    "rdMLabel": "Görüş Mesafesi",
    "spSurv": "HAY. KALMA",
    "spCrea": "YARATICI",
    "spAdv": "MACERA",
    "crouchBtn": "ÇÖMEL",
    "worldSectionLabel": "DÜNYA",
    "gameModeSectionLabel": "OYUN MODU",
    "cheatsLabel": "HİLELER",
    "cheatOff": "KAPALI",
    "cheatOn": "AÇIK",
    "deathTitle": "Öldün!",
    "respawnBtn": "Yeniden Doğ",
    "pauseSettings": "AYARLAR",
    "mpBrowse": "GÖZ AT",
    "mpLoad": "YÜKLE",
    "mpCreate": "OLUŞTUR",
    "mpServerList": "SUNUCU LİSTESİ",
    "invTitle": "ENVANTER",
    "invBlocks": "BLOKLAR",
    "invHint": "HOTBAR – ATAMAK İÇİN BLOK SEÇ, SONRA SLOTA TIKLA",
    "invClose": "[E] kapat",
    "bkNames": [
      "Tahta",
      "Çimen",
      "Toprak",
      "Taş",
      "Odun",
      "Karaktas",
      "Cam",
      "Yaprak",
      "Kum",
      "Su",
      "Kaya Dibi",
      "Lav",
      "Obsidyen",
      "Andezit",
      "Granit",
      "Diorit",
      "Çakıl"
    ],
    "settingsPcBtn": "PC AYARLARI",
    "settingsMobileBtn": "MOBİL AYARLAR",
    "pcSettingsTitle": "PC AYARLARI",
    "mobileSettingsTitle": "MOBİL AYARLAR",
    "sensLabel": "Hassasiyet",
    "fovLabel": "Görüş Açısı (FOV)",
    "keybindsTitle": "TUŞ ATAMALARI",
    "kbForward": "İleri",
    "kbBack": "Geri",
    "kbLeft": "Sol",
    "kbRight": "Sağ",
    "kbJump": "Zıpla",
    "kbSlot": "Slot Seç",
    "kbBreak": "Blok Kır",
    "kbPlace": "Blok Koy",
    "kbChat": "Sohbet",
    "kbPause": "Duraklat",
    "srvPrefix": "[Sunucu]: ",
    "srvNoCheat": "[Sunucu]: Hileler kapalı!",
    "srvNoPerms": "[Sunucu]: Yetkiniz yok!",
    "srvHostOnly": "[Sunucu]: Sadece yönetici!",
    "srvUsageMode": "Kullanım: /mode c, /mode s veya /mode a",
    "srvUsageOp": "Kullanım: /op <isim>",
    "srvUsageUnop": "Kullanım: /unop <isim>",
    "srvUsageKick": "Kullanım: /kick <isim>",
    "srvUsageBan": "Kullanım: /ban <isim>",
    "srvNoPlayer": "[Sunucu]: Oyuncu bulunamadı: ",
    "srvNoCantKickOp": "[Sunucu]: Operatörleri atamazsınız!",
    "srvNoCantBanOp": "[Sunucu]: Operatörleri banlayamazsınız!",
    "srvUnknownCmd": "Bilinmeyen komut: /",
    "srvUnknownEntity": "Bilinmeyen varlık: ",
    "srvUsageSummon": "Kullanım: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Varlık spawn edilemedi (chunk yüklü değil).",
    "srvSummonSuccess": "%e spawn edildi: (%x, %y, %z)",
    "srvFriendUsage": "Kullanım: /friend <oyuncuİsmi>",
    "srvFriendSent": "Arkadaşlık isteği gönderildi!",
    "srvFriendGuest": "Kayıtlı olmayan oyuncuya arkadaşlık isteği atamazsın!",
    "srvFriendSelf": "Kendine arkadaşlık isteği atamazsın!",
    "srvModeChanged": "Mod: ",
    "srvOpGranted": " artık operatör!",
    "srvOpRevoked": " operatörlüğü alındı.",
    "srvKicked": " sunucudan atıldı.",
    "srvBanned": " banlandı.",
    "srvUnbanned": " banı kaldırıldı.",
    "srvKickedBy": " tarafından atıldınız.",
    "srvOpBecame": " operatör oldu",
    "srvOpLost": " operatörlüğü kaybetti",
    "srvKickedNotice": "Sunucudan çıkarıldınız: ",
    "banScreenTitle": "Bu Sunucudan Yasaklandın!",
    "kickScreenTitle": "Sunucudan Atıldın!",
    "banByText": " sizi yasakladı!",
    "kickByText": " sizi attı!",
    "backToMenuBtn": "Ana Menüye Dön",
    "rateLimitMsg": "Çok hızlı mesaj gönderiyorsunuz!",
    "deathMessages": {
      "fall": "Yüksek düşüş",
      "suffocation": "Sıkışma",
      "void": "Boşluk",
      "pvp": "PvP",
      "lava": "Lav",
      "fire": "Ateş",
      "unknown": "Bilinmeyen neden"
    },
    "deathChat": {
      "pvp": "%V%, %A% tarafından öldürüldü",
      "suffocation": "%V% blokların arasına sıkışarak öldü",
      "void": "%V% boşluktan düşerek öldü",
      "fall": "%V% yüksekten düşerek öldü",
      "lava": "%V% lavda yanarak öldü",
      "fire": "%V% ateşte yanarak öldü"
    },
    "killDeathMsg": "Oyuncu öldü",
    "killAllMsg": "[Sunucu]: Tüm oyuncular öldürüldü",
    "srvUsageKillCmd": "Kullanım: /kill | /kill @p | /kill @a | /kill <isim>",
    "srvKillNoPlayer": "[Sunucu]: Oyuncu bulunamadı: ",
    "srvCheatsOn": "[Sunucu]: Hileler açıldı!",
    "srvCheatsOff": "[Sunucu]: Hileler kapatıldı!",
    "srvUsageCheats": "Kullanım: /cheats on veya /cheats off",
    "srvCheatsHostOnly": "[Sunucu]: Hileler sadece yönetici tarafından değiştirilebilir!",
    "srvMpOnlyCmd": "[Sunucu]: Bu komud sadece çok oyunculuda kullanılabilir",
    "srvCheatsSpOnly": "[Sunucu]: Hileler menüden açılıp kapatılabilir!",
    "srvShoutNoPerm": "Bu komut Twitch ve üzeri rütbeler içindir",
    "srvUsageShout": "Kullanım: /shout <mesaj>",
    "camFirstPerson": "🎥 1. Şahıs",
    "camThirdBack": "🎥 3. Şahıs (Arka)",
    "camThirdFront": "🎥 3. Şahıs (Ön)",
    "skinTitle": "SKİN AYARLARI",
    "skinPreview": "ÖNİZLEME",
    "skinUploader": "SKİN YÜKLEYİCİ",
    "skinUploadHint": "📁 Minecraft skin PNG yükle",
    "skinUploadSize": "64×64, 64×32 veya 128×128 piksel",
    "skinChoose": "📂 DOSYA SEÇ",
    "skinReset": "🔄 STEVE'E SIFIRLA",
    "skinMenuBtn": "🎨 ÖZEL SKİN",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Skin çok oyunculu modda diğer oyuncular tarafından görülebilir.",
    "skinLoaded": "✅ Skin yüklendi!",
    "skinError": "❌ Hata: 64×64, 64×32 veya 128×128 PNG olmalı.",
    "skinGuestWarning": "🔒 Özel skin yüklemek için hesap gerekli.",
    "skinGuestHint": "Hesap sahibiyseniz siteye giriş yapın.",
    "heightLimitMsg": "⛔ Yapı yükseklik limitine ulaşıldı! (250 Blok)",
    "worldBorderMsg": "⛔ Dünya sınırına ulaştınız!",
    "giveUsage": "Kullanım: /give <hedef> <blok>",
    "giveUnknownBlock": "Bilinmeyen blok: ",
    "giveSuccess": "Verildi: ",
    "giveNoTarget": "Hedef bulunamadı: ",
    "helpTitle": "─── KOMUTLAR ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Mod değiştir (creative/survival/adventure/spectator)",
      "/give <@p|@a|isim> <blok>  →  Blok ver",
      "/kill [@p|@a|isim]  →  Oyuncu öldür",
      "/op <isim>  →  Operatör ver",
      "/unop <isim>  →  Operatörlük al",
      "/kick <isim>  →  At",
      "/ban <isim>  →  Banla",
      "/unban <isim>  →  Banı kaldır",
      "/setworldspawn  →  Doğma noktasını ayarla",
      "/setblock <x> <y> <z> <blok>  →  Belirtilen konuma blok koy",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <blok>  →  Alanı blokla doldur",
      "/summon <sheep|cow|pig> [x y z]  →  Varlık spawn et",
      "/friend <isim>  →  Arkadaşlık isteği",
      "/shout <mesaj>  →  Global mesaj",
      "/help  →  Bu menüyü göster"
    ],
    "tmTitle": "TEST AŞAMASI",
    "tmDesc": "Giriş yapmadınız. Normal koşullarda bu işlem hesap gerektirir.<br><br>Oyun <strong style=\"color:#ffc84a\">Geliştirme / Test</strong> aşamasında olduğundan hesapsız devam edebilirsiniz. Ancak bu sürüm <strong style=\"color:#ff7a7a\">hatalar ve eksiklikler içerebilir</strong>, veriler misafir olarak gönderilecektir.",
    "tmContinue": "YINE DE DEVAM ET",
    "tmCancel": "İPTAL",
    "guestCreateTitle": "Sunucu oluşturmak için hesap gereklidir.",
    "guestCreateHint": "Siteye giriş yaparak bu özelliği kullanabilirsiniz.",
    "guestLoadMsg": "🔒 Dünya yüklemek için hesap gereklidir.",
    "guestCreateMsg": "🔒 Sunucu oluşturmak için hesap gereklidir. Lütfen siteye giriş yapın.",
    "slTitle": "SUNUCU LİSTESİ",
    "slSavedWorld": "KAYITLI DÜNYA SEÇ",
    "slNoBrowser": "Tarayıcıda kayıtlı dünya bulunamadı.",
    "slServerSettings": "SUNUCU AYARLARI",
    "slLoadHost": "YÜKLE & HOST",
    "slWorldLoading": "Dünya yükleniyor...",
    "slWorldReadError": "⚠ Dünya verisi okunamadı.",
    "slServerError": "⚠ Sunucu hatası: ",
    "slSearchPh": "Sunucu ara...",
    "slConnecting": "Sunucular yükleniyor...",
    "slNoResponse": "⚠ Sunucudan yanıt gelmedi.",
    "slNoServers": "Aktif sunucu bulunamadı.",
    "slCreateServer": "⚙️ SUNUCU OLUŞTUR",
    "msTitle": "⚙ SUNUCUYU YÖNET",
    "msTabPlayers": "👥 OYUNCULAR",
    "msTabAdmins": "🛡 ADMİNLER & BANLILAR",
    "msTabServer": "⚙ SUNUCU",
    "msBtnManage": "🛡 SUNUCUYU YÖNET",
    "msLblAdmins": "ADMİNLER",
    "msLblBanned": "BANLILAR",
    "msLblAccess": "Erişim",
    "msLblPvp": "PvP",
    "msLblCheats": "Hileler",
    "msOptPublic": "🌐 Herkese Açık",
    "msOptRegistered": "🔑 Sadece Hesaplılar",
    "msOptPrivate": "🔒 Özel",
    "msBtnPromote": "Promote",
    "msBtnDemote": "Demote",
    "msBtnKick": "At",
    "msBtnBan": "Banla",
    "msBtnUnban": "Banı Kaldır",
    "msBtnShutdown": "🛑 SUNUCUYU KAPAT",
    "msBtnClose": "← KAPAT",
    "msNoPlayers": "Sunucuda oyuncu yok.",
    "msNoAdmins": "Admin yok.",
    "msNoBanned": "Banlı oyuncu yok.",
    "msPvpOn": "AÇIK",
    "msPvpOff": "KAPALI",
    "msCheatsOn": "AÇIK",
    "msCheatsOff": "KAPALI",
    "hcModLabel": "HARDCORE MOD",
    "hcOn": "AÇIK",
    "hcOff": "KAPALI",
    "hcWatchWorld": "Dünyayı İzle",
    "hcMainMenu": "Ana Menüye Dön",
    "hcBlockedGeneric": "⛔ Hardcore modunda bu komut kullanılamaz.",
    "hcBlockedSpectator": "⛔ Hardcore modunda kullanılamaz.",
    "specModeSet": "Oyun modu: Hayalet.",
    "hcWorldEnded": "💀 Bu Hardcore dünya sona erdi. Sadece izleyebilirsin.",
    "spStateRestored": "💾 Dünya durumu geri yüklendi.",
    "spDeadTag": "☠ ÖLDÜ",
    "spDeadTooltip": "İzleme modunda açılır",
    "myWorldsTitle": "DÜNYALARIM",
    "newWorldBtn": "➕ YENİ DÜNYA OLUŞTUR",
    "noWorldsYet": "Henüz kaydedilmiş dünya yok.",
    "noWorldsHint": "Yeni bir dünya oluştur veya oyna.",
    "editWorldName": "DÜNYA ADI",
    "editWorldNamePh": "Dünya Adı...",
    "editWorldType": "DÜNYA TİPİ",
    "editGameMode": "OYUN MODU",
    "editCheats": "HİLELER",
    "saveBtn": "💾 KAYDET",
    "cancelBtn": "✖ VAZGEÇ",
    "wtNormal": "NORMAL",
    "wtFlat": "DÜZ",
    "wtSmall": "KÜÇÜK",
    "gmSurvival": "HAY.KALMA",
    "gmCreative": "YARATİCİ",
    "gmAdventure": "MACERA",
    "chOff": "KAPALI",
    "chOn": "AÇIK",
    "f3Fps": "FPS",
    "f3Xyz": "Koordinat",
    "f3Block": "Blok",
    "f3Chunk": "Chunk",
    "f3Facing": "Yön",
    "f3Pitch": "Eğim",
    "f3Biome": "Biyom",
    "f3Targeted": "Hedeflenen",
    "f3World": "Dünya",
    "f3Seed": "Tohum",
    "f3Mode": "Mod",
    "f3Flying": "Uçuş",
    "f3Grounded": "Yerde",
    "f3Chunks": "Chunk Sayısı",
    "controlsTabLabel": "Kontroller",
    "languageTabLabel": "Dil"
  },
  "de": {
    "title": "LEGENDS INDEV",
    "singleplayer": "EINZELSPIELER",
    "multiplayer": "MEHRSPIELER",
    "settings": "EINSTELLUNGEN",
    "deviceTitle": "GERÄT WÄHLEN",
    "pcBtn": "COMPUTER",
    "mobileBtn": "MOBIL",
    "worldTitle": "WELT WÄHLEN",
    "wInfTitle": "NORMALE WELT",
    "wInfDesc": "Perlin-Noise-Gelände",
    "wSmTitle": "KLEINE WELT",
    "wSmDesc": "Leicht und schnell",
    "wFlatTitle": "FLACHE WELT",
    "wFlatDesc": "Vollständig flaches Gelände",
    "back": "← ZURÜCK",
    "errTitle": "Grafik-Engine-Fehler!",
    "errDesc": "Bitte überprüfe deine Internetverbindung.",
    "resume": "FORTSETZEN",
    "quit": "BEENDEN",
    "pauseTitle": "SPIELMENÜ",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "SPRINGEN",
    "mpTitle": "MEHRSPIELER",
    "mpJoin": "BEITRETEN",
    "mpHost": "HOSTEN",
    "settingsTitle": "EINSTELLUNGEN",
    "joinTitle": "RAUM BEITRETEN",
    "joinNamePh": "Dein Spielername",
    "joinCodePh": "4-STELLIGER CODE",
    "joinBtn": "BEITRETEN",
    "hostTitle": "RAUM HOSTEN",
    "hostNamePh": "Dein Spielername",
    "hostStart": "RAUM STARTEN",
    "codeLabel": "RAUMCODE",
    "wmcInf": "NORMAL",
    "wmcFlat": "FLACH",
    "wmcSm": "KLEIN",
    "gmcSurv": "ÜBERLEBEN",
    "gmcCrea": "KREATIV",
    "gmcAdv": "ABENTEUER",
    "chatHint": "⌨  Enter → Chat",
    "chatPh": "Nachricht eingeben...",
    "sysJoin": " ist beigetreten",
    "sysLeft": " hat verlassen",
    "sysDisc": "Verbindung verloren",
    "sysSpawnSet": "✅ Weltspawnpunkt aktualisiert!",
    "sysSpawnSetUsage": "Verwendung: /setworldspawn (muss Host sein)",
    "srvUsageSetblock": "Verwendung: /setblock <x> <y> <z> <block>",
    "srvSetblockSuccess": "✅ Block platziert bei: ",
    "srvUsageFill": "Verwendung: /fill <x1> <y1> <z1> <x2> <y2> <z2> <block>",
    "srvFillSuccess": "✅ Bereich gefüllt, Blockanzahl: ",
    "srvFillTooLarge": "⚠️ Zu viele Blöcke (Limit überschritten): ",
    "crosshairModeLabel": "🎯 Fadenkreuz-Modus",
    "crosshairModeSublabel": "(Block in der Mitte platzieren)",
    "srvSpawnCodeMissing": "⚠️ Raumcode nicht gefunden, Server nicht erreichbar.",
    "srvSpawnNoConnection": "⚠️ Nicht mit Server verbunden.",
    "srvSpawnFailed": "⚠️ Spawnpunkt konnte nicht gesetzt werden: ",
    "sysPlayerSaved": "💾 Position und Inventar gespeichert.",
    "modeCreative": "Kreativmodus",
    "modeSurvival": "Überlebensmodus",
    "modeAdventure": "Abenteuermodus",
    "rdLabel": "Sichtweite",
    "rdPcLabel": "Sichtweite",
    "rdMLabel": "Sichtweite",
    "spSurv": "ÜBERLEBEN",
    "spCrea": "KREATIV",
    "spAdv": "ABENTEUER",
    "crouchBtn": "DUCKEN",
    "worldSectionLabel": "WELT",
    "gameModeSectionLabel": "SPIELMODUS",
    "cheatsLabel": "CHEATS",
    "cheatOff": "AUS",
    "cheatOn": "AN",
    "deathTitle": "Du bist gestorben!",
    "respawnBtn": "Wiedergeburt",
    "pauseSettings": "EINSTELLUNGEN",
    "mpBrowse": "DURCHSUCHEN",
    "mpLoad": "LADEN",
    "mpCreate": "ERSTELLEN",
    "mpServerList": "SERVERLISTE",
    "invTitle": "INVENTAR",
    "invBlocks": "BLÖCKE",
    "invHint": "HOTBAR – BLOCK WÄHLEN, DANN AUF SLOT KLICKEN ZUM ZUWEISEN",
    "invClose": "[E] schließen",
    "bkNames": [
      "Bretter",
      "Gras",
      "Erde",
      "Stein",
      "Baumstamm",
      "Bruchstein",
      "Glas",
      "Laub",
      "Sand",
      "Wasser",
      "Grundgestein",
      "Lava",
      "Obsidian",
      "Andesit",
      "Granit",
      "Diorit",
      "Kies"
    ],
    "settingsPcBtn": "PC-EINSTELLUNGEN",
    "settingsMobileBtn": "MOBIL-EINSTELLUNGEN",
    "pcSettingsTitle": "PC-EINSTELLUNGEN",
    "mobileSettingsTitle": "MOBIL-EINSTELLUNGEN",
    "sensLabel": "Empfindlichkeit",
    "fovLabel": "Sichtfeld (FOV)",
    "keybindsTitle": "TASTENBELEGUNG",
    "kbForward": "Vorwärts",
    "kbBack": "Rückwärts",
    "kbLeft": "Links",
    "kbRight": "Rechts",
    "kbJump": "Springen",
    "kbSlot": "Slot wählen",
    "kbBreak": "Block abbauen",
    "kbPlace": "Block platzieren",
    "kbChat": "Chat",
    "kbPause": "Pause",
    "srvPrefix": "[Server]: ",
    "srvNoCheat": "[Server]: Cheats sind deaktiviert!",
    "srvNoPerms": "[Server]: Du hast keine Berechtigung!",
    "srvHostOnly": "[Server]: Nur für Host!",
    "srvUsageMode": "Verwendung: /mode c, /mode s oder /mode a",
    "srvUsageOp": "Verwendung: /op <name>",
    "srvUsageUnop": "Verwendung: /unop <name>",
    "srvUsageKick": "Verwendung: /kick <name>",
    "srvUsageBan": "Verwendung: /ban <name>",
    "srvNoPlayer": "[Server]: Spieler nicht gefunden: ",
    "srvNoCantKickOp": "[Server]: Operatoren können nicht gekickt werden!",
    "srvNoCantBanOp": "[Server]: Operatoren können nicht gebannt werden!",
    "srvUnknownCmd": "Unbekannter Befehl: /",
    "srvUnknownEntity": "Unbekannte Einheit: ",
    "srvUsageSummon": "Verwendung: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Einheit konnte nicht gespawnt werden (Chunk nicht geladen).",
    "srvSummonSuccess": "%e gespawnt bei (%x, %y, %z)",
    "srvFriendUsage": "Verwendung: /friend <spielername>",
    "srvFriendSent": "Freundschaftsanfrage gesendet!",
    "srvFriendGuest": "Freundschaftsanfrage an unregistrierte Spieler nicht möglich!",
    "srvFriendSelf": "Du kannst dir selbst keine Freundschaftsanfrage senden!",
    "srvModeChanged": "Modus: ",
    "srvOpGranted": " ist jetzt Operator!",
    "srvOpRevoked": " ist kein Operator mehr.",
    "srvKicked": " wurde gekickt.",
    "srvBanned": " wurde gebannt.",
    "srvUnbanned": " wurde entbannt.",
    "srvKickedBy": " hat dich gekickt.",
    "srvOpBecame": " wurde Operator",
    "srvOpLost": " ist kein Operator mehr",
    "srvKickedNotice": "Du wurdest vom Server entfernt: ",
    "banScreenTitle": "Du wurdest von diesem Server gebannt!",
    "kickScreenTitle": "Du wurdest vom Server gekickt!",
    "banByText": " hat dich gebannt!",
    "kickByText": " hat dich gekickt!",
    "backToMenuBtn": "Zurück zum Hauptmenü",
    "rateLimitMsg": "Du sendest Nachrichten zu schnell!",
    "deathMessages": {
      "fall": "Hoher Sturz",
      "suffocation": "Erstickung",
      "void": "Leere",
      "pvp": "PvP",
      "lava": "Lava",
      "fire": "Feuer",
      "unknown": "Unbekannt"
    },
    "deathChat": {
      "pvp": "%V% wurde von %A% getötet",
      "suffocation": "%V% ist in einer Wand erstickt",
      "void": "%V% ist aus der Welt gefallen",
      "fall": "%V% ist aus großer Höhe gefallen",
      "lava": "%V% ist in Lava verbrannt",
      "fire": "%V% ist verbrannt"
    },
    "killDeathMsg": "Spieler gestorben",
    "killAllMsg": "[Server]: Alle Spieler wurden getötet",
    "srvUsageKillCmd": "Verwendung: /kill | /kill @p | /kill @a | /kill <name>",
    "srvKillNoPlayer": "[Server]: Spieler nicht gefunden: ",
    "srvCheatsOn": "[Server]: Cheats aktiviert!",
    "srvCheatsOff": "[Server]: Cheats deaktiviert!",
    "srvUsageCheats": "Verwendung: /cheats on oder /cheats off",
    "srvCheatsHostOnly": "[Server]: Nur der Host kann Cheats ändern!",
    "srvMpOnlyCmd": "[Server]: Dieser Befehl ist nur im Mehrspieler verfügbar",
    "srvCheatsSpOnly": "[Server]: Cheats können im Menü umgeschaltet werden!",
    "srvShoutNoPerm": "Dieser Befehl ist für Twitch-Rang und höher",
    "srvUsageShout": "Verwendung: /shout <nachricht>",
    "camFirstPerson": "🎥 Ich-Perspektive",
    "camThirdBack": "🎥 3. Person (Hinten)",
    "camThirdFront": "🎥 3. Person (Vorne)",
    "skinTitle": "SKIN-EINSTELLUNGEN",
    "skinPreview": "VORSCHAU",
    "skinUploader": "SKIN-UPLOADER",
    "skinUploadHint": "📁 Minecraft-Skin-PNG hochladen",
    "skinUploadSize": "64×64, 64×32 oder 128×128 Pixel",
    "skinChoose": "📂 DATEI WÄHLEN",
    "skinReset": "🔄 AUF STEVE ZURÜCKSETZEN",
    "skinMenuBtn": "🎨 EIGENER SKIN",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Dein Skin ist für andere Spieler im Mehrspieler sichtbar.",
    "skinLoaded": "✅ Skin geladen!",
    "skinError": "❌ Fehler: Muss ein 64×64-, 64×32- oder 128×128-PNG sein.",
    "skinGuestWarning": "🔒 Für einen eigenen Skin ist ein Konto erforderlich.",
    "skinGuestHint": "Melde dich auf der Seite an, falls du ein Konto hast.",
    "heightLimitMsg": "⛔ Bauhöhenlimit erreicht! (250 Blöcke)",
    "worldBorderMsg": "⛔ Du hast die Weltgrenze erreicht!",
    "giveUsage": "Verwendung: /give <ziel> <block>",
    "giveUnknownBlock": "Unbekannter Block: ",
    "giveSuccess": "Gegeben: ",
    "giveNoTarget": "Ziel nicht gefunden: ",
    "helpTitle": "─── BEFEHLE ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Modus wechseln (creative/survival/adventure/spectator)",
      "/give <@p|@a|name> <block>  →  Block geben",
      "/kill [@p|@a|name]  →  Spieler töten",
      "/op <name>  →  Operator gewähren",
      "/unop <name>  →  Operator entziehen",
      "/kick <name>  →  Spieler kicken",
      "/ban <name>  →  Spieler bannen",
      "/unban <name>  →  Bann aufheben",
      "/setworldspawn  →  Weltspawnpunkt setzen",
      "/setblock <x> <y> <z> <block>  →  Block an Position setzen",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <block>  →  Bereich mit Block füllen",
      "/summon <sheep|cow|pig> [x y z]  →  Einheit spawnen",
      "/friend <name>  →  Freundschaftsanfrage",
      "/shout <nachricht>  →  Globale Nachricht",
      "/help  →  Dieses Menü anzeigen"
    ],
    "tmTitle": "TESTPHASE",
    "tmDesc": "Du bist nicht angemeldet. Normalerweise erfordert diese Aktion ein Konto.<br><br>Da sich das Spiel in der <strong style=\"color:#ffc84a\">Entwicklungs-/Testphase</strong> befindet, kannst du ohne Konto fortfahren. Diese Version <strong style=\"color:#ff7a7a\">kann jedoch Fehler und fehlende Funktionen enthalten</strong>, Daten werden als Gast gesendet.",
    "tmContinue": "TROTZDEM FORTFAHREN",
    "tmCancel": "ABBRECHEN",
    "guestCreateTitle": "Für das Erstellen eines Servers ist ein Konto erforderlich.",
    "guestCreateHint": "Melde dich auf der Seite an, um diese Funktion zu nutzen.",
    "guestLoadMsg": "🔒 Für das Laden einer Welt ist ein Konto erforderlich.",
    "guestCreateMsg": "🔒 Für das Erstellen eines Servers ist ein Konto erforderlich. Bitte melde dich an.",
    "slTitle": "SERVERLISTE",
    "slSavedWorld": "GESPEICHERTE WELT WÄHLEN",
    "slNoBrowser": "Keine gespeicherten Welten im Browser gefunden.",
    "slServerSettings": "SERVEREINSTELLUNGEN",
    "slLoadHost": "LADEN & HOSTEN",
    "slWorldLoading": "Welt wird geladen...",
    "slWorldReadError": "⚠ Weltdaten konnten nicht gelesen werden.",
    "slServerError": "⚠ Serverfehler: ",
    "slSearchPh": "Server suchen...",
    "slConnecting": "Server werden geladen...",
    "slNoResponse": "⚠ Keine Antwort vom Server.",
    "slNoServers": "Keine aktiven Server gefunden.",
    "slCreateServer": "⚙️ SERVER ERSTELLEN",
    "msTitle": "⚙ SERVER VERWALTEN",
    "msTabPlayers": "👥 SPIELER",
    "msTabAdmins": "🛡 ADMINS & BANNS",
    "msTabServer": "⚙ SERVER",
    "msBtnManage": "🛡 SERVER VERWALTEN",
    "msLblAdmins": "ADMINS",
    "msLblBanned": "GEBANNT",
    "msLblAccess": "Zugriff",
    "msLblPvp": "PvP",
    "msLblCheats": "Cheats",
    "msOptPublic": "🌐 Öffentlich",
    "msOptRegistered": "🔑 Nur Registrierte",
    "msOptPrivate": "🔒 Privat",
    "msBtnPromote": "Befördern",
    "msBtnDemote": "Degradieren",
    "msBtnKick": "Kicken",
    "msBtnBan": "Bannen",
    "msBtnUnban": "Entbannen",
    "msBtnShutdown": "🛑 SERVER HERUNTERFAHREN",
    "msBtnClose": "← SCHLIESSEN",
    "msNoPlayers": "Keine Spieler auf dem Server.",
    "msNoAdmins": "Keine Admins.",
    "msNoBanned": "Keine gebannten Spieler.",
    "msPvpOn": "AN",
    "msPvpOff": "AUS",
    "msCheatsOn": "AN",
    "msCheatsOff": "AUS",
    "hcModLabel": "HARDCORE-MODUS",
    "hcOn": "AN",
    "hcOff": "AUS",
    "hcWatchWorld": "Welt beobachten",
    "hcMainMenu": "Zurück zum Hauptmenü",
    "hcBlockedGeneric": "⛔ Befehle sind im Hardcore-Modus gesperrt.",
    "hcBlockedSpectator": "⛔ Im Hardcore-Modus gesperrt.",
    "specModeSet": "Spielmodus auf Zuschauer gesetzt.",
    "hcWorldEnded": "💀 Diese Hardcore-Welt ist beendet. Du kannst nur zuschauen.",
    "spStateRestored": "💾 Weltzustand wiederhergestellt.",
    "spDeadTag": "☠ TOT",
    "spDeadTooltip": "Öffnet im Zuschauermodus",
    "myWorldsTitle": "MEINE WELTEN",
    "newWorldBtn": "➕ NEUE WELT ERSTELLEN",
    "noWorldsYet": "Noch keine gespeicherten Welten.",
    "noWorldsHint": "Erstelle oder spiele eine neue Welt.",
    "editWorldName": "WELTNAME",
    "editWorldNamePh": "Weltname...",
    "editWorldType": "WELTTYP",
    "editGameMode": "SPIELMODUS",
    "editCheats": "CHEATS",
    "saveBtn": "💾 SPEICHERN",
    "cancelBtn": "✖ ABBRECHEN",
    "wtNormal": "NORMAL",
    "wtFlat": "FLACH",
    "wtSmall": "KLEIN",
    "gmSurvival": "ÜBERLEBEN",
    "gmCreative": "KREATIV",
    "gmAdventure": "ABENTEUER",
    "chOff": "AUS",
    "chOn": "AN",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Block",
    "f3Chunk": "Chunk",
    "f3Facing": "Blickrichtung",
    "f3Pitch": "Neigung",
    "f3Biome": "Biom",
    "f3Targeted": "Anvisiert",
    "f3World": "Welt",
    "f3Seed": "Seed",
    "f3Mode": "Modus",
    "f3Flying": "Fliegen",
    "f3Grounded": "Am Boden",
    "f3Chunks": "Chunks",
    "controlsTabLabel": "Steuerung",
    "languageTabLabel": "Sprache"
  },
  "fr": {
    "title": "LEGENDS INDEV",
    "singleplayer": "SOLO",
    "multiplayer": "MULTIJOUEUR",
    "settings": "PARAMÈTRES",
    "deviceTitle": "CHOISIR L'APPAREIL",
    "pcBtn": "ORDINATEUR",
    "mobileBtn": "MOBILE",
    "worldTitle": "CHOISIR LE MONDE",
    "wInfTitle": "MONDE NORMAL",
    "wInfDesc": "Terrain en bruit de Perlin",
    "wSmTitle": "PETIT MONDE",
    "wSmDesc": "Léger et rapide",
    "wFlatTitle": "MONDE PLAT",
    "wFlatDesc": "Terrain entièrement plat",
    "back": "← RETOUR",
    "errTitle": "Erreur du moteur graphique !",
    "errDesc": "Veuillez vérifier votre connexion internet.",
    "resume": "REPRENDRE",
    "quit": "QUITTER",
    "pauseTitle": "MENU DU JEU",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "SAUTER",
    "mpTitle": "MULTIJOUEUR",
    "mpJoin": "REJOINDRE",
    "mpHost": "HÉBERGER",
    "settingsTitle": "PARAMÈTRES",
    "joinTitle": "REJOINDRE UN SALON",
    "joinNamePh": "Votre nom de joueur",
    "joinCodePh": "CODE À 4 LETTRES",
    "joinBtn": "REJOINDRE",
    "hostTitle": "HÉBERGER UN SALON",
    "hostNamePh": "Votre nom de joueur",
    "hostStart": "DÉMARRER LE SALON",
    "codeLabel": "CODE DU SALON",
    "wmcInf": "NORMAL",
    "wmcFlat": "PLAT",
    "wmcSm": "PETIT",
    "gmcSurv": "SURVIE",
    "gmcCrea": "CRÉATIF",
    "gmcAdv": "AVENTURE",
    "chatHint": "⌨  Entrée → Chat",
    "chatPh": "Tapez un message...",
    "sysJoin": " a rejoint",
    "sysLeft": " a quitté",
    "sysDisc": "Connexion perdue",
    "sysSpawnSet": "✅ Point d'apparition du monde mis à jour !",
    "sysSpawnSetUsage": "Usage : /setworldspawn (doit être l'hôte)",
    "srvUsageSetblock": "Usage : /setblock <x> <y> <z> <bloc>",
    "srvSetblockSuccess": "✅ Bloc placé à : ",
    "srvUsageFill": "Usage : /fill <x1> <y1> <z1> <x2> <y2> <z2> <bloc>",
    "srvFillSuccess": "✅ Zone remplie, nombre de blocs : ",
    "srvFillTooLarge": "⚠️ Trop de blocs (limite dépassée) : ",
    "crosshairModeLabel": "🎯 Mode Réticule",
    "crosshairModeSublabel": "(placer le bloc au centre)",
    "srvSpawnCodeMissing": "⚠️ Code de salon introuvable, serveur inaccessible.",
    "srvSpawnNoConnection": "⚠️ Non connecté au serveur.",
    "srvSpawnFailed": "⚠️ Impossible de définir le point d'apparition : ",
    "sysPlayerSaved": "💾 Position et inventaire sauvegardés.",
    "modeCreative": "Mode Créatif",
    "modeSurvival": "Mode Survie",
    "modeAdventure": "Mode Aventure",
    "rdLabel": "Distance d'affichage",
    "rdPcLabel": "Distance d'affichage",
    "rdMLabel": "Distance d'affichage",
    "spSurv": "SURVIE",
    "spCrea": "CRÉATIF",
    "spAdv": "AVENTURE",
    "crouchBtn": "S'ACCROUPIR",
    "worldSectionLabel": "MONDE",
    "gameModeSectionLabel": "MODE DE JEU",
    "cheatsLabel": "TRICHES",
    "cheatOff": "DÉSACTIVÉ",
    "cheatOn": "ACTIVÉ",
    "deathTitle": "Vous êtes mort !",
    "respawnBtn": "Réapparaître",
    "pauseSettings": "PARAMÈTRES",
    "mpBrowse": "PARCOURIR",
    "mpLoad": "CHARGER",
    "mpCreate": "CRÉER",
    "mpServerList": "LISTE DES SERVEURS",
    "invTitle": "INVENTAIRE",
    "invBlocks": "BLOCS",
    "invHint": "BARRE D'OUTILS – CHOISISSEZ UN BLOC PUIS CLIQUEZ UN EMPLACEMENT",
    "invClose": "[E] fermer",
    "bkNames": [
      "Planches",
      "Herbe",
      "Terre",
      "Pierre",
      "Bûche",
      "Pierre taillée",
      "Verre",
      "Feuilles",
      "Sable",
      "Eau",
      "Roche-mère",
      "Lave",
      "Obsidienne",
      "Andésite",
      "Granite",
      "Diorite",
      "Gravier"
    ],
    "settingsPcBtn": "PARAMÈTRES PC",
    "settingsMobileBtn": "PARAMÈTRES MOBILE",
    "pcSettingsTitle": "PARAMÈTRES PC",
    "mobileSettingsTitle": "PARAMÈTRES MOBILE",
    "sensLabel": "Sensibilité",
    "fovLabel": "Champ de vision (FOV)",
    "keybindsTitle": "RACCOURCIS CLAVIER",
    "kbForward": "Avancer",
    "kbBack": "Reculer",
    "kbLeft": "Gauche",
    "kbRight": "Droite",
    "kbJump": "Sauter",
    "kbSlot": "Choisir emplacement",
    "kbBreak": "Casser un bloc",
    "kbPlace": "Placer un bloc",
    "kbChat": "Chat",
    "kbPause": "Pause",
    "srvPrefix": "[Serveur] : ",
    "srvNoCheat": "[Serveur] : Les triches sont désactivées !",
    "srvNoPerms": "[Serveur] : Vous n'avez pas la permission !",
    "srvHostOnly": "[Serveur] : Réservé à l'hôte !",
    "srvUsageMode": "Usage : /mode c, /mode s ou /mode a",
    "srvUsageOp": "Usage : /op <nom>",
    "srvUsageUnop": "Usage : /unop <nom>",
    "srvUsageKick": "Usage : /kick <nom>",
    "srvUsageBan": "Usage : /ban <nom>",
    "srvNoPlayer": "[Serveur] : Joueur introuvable : ",
    "srvNoCantKickOp": "[Serveur] : Impossible d'expulser un opérateur !",
    "srvNoCantBanOp": "[Serveur] : Impossible de bannir un opérateur !",
    "srvUnknownCmd": "Commande inconnue : /",
    "srvUnknownEntity": "Entité inconnue : ",
    "srvUsageSummon": "Usage : /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Impossible de faire apparaître l'entité (chunk non chargé).",
    "srvSummonSuccess": "%e apparu à (%x, %y, %z)",
    "srvFriendUsage": "Usage : /friend <nomJoueur>",
    "srvFriendSent": "Demande d'ami envoyée !",
    "srvFriendGuest": "Impossible d'envoyer une demande d'ami à un joueur non inscrit !",
    "srvFriendSelf": "Vous ne pouvez pas vous envoyer une demande d'ami !",
    "srvModeChanged": "Mode : ",
    "srvOpGranted": " est maintenant opérateur !",
    "srvOpRevoked": " n'est plus opérateur.",
    "srvKicked": " a été expulsé.",
    "srvBanned": " a été banni.",
    "srvUnbanned": " a été débanni.",
    "srvKickedBy": " vous a expulsé.",
    "srvOpBecame": " est devenu opérateur",
    "srvOpLost": " n'est plus opérateur",
    "srvKickedNotice": "Vous avez été retiré du serveur : ",
    "banScreenTitle": "Vous avez été banni de ce serveur !",
    "kickScreenTitle": "Vous avez été expulsé du serveur !",
    "banByText": " vous a banni !",
    "kickByText": " vous a expulsé !",
    "backToMenuBtn": "Retour au menu principal",
    "rateLimitMsg": "Vous envoyez des messages trop vite !",
    "deathMessages": {
      "fall": "Chute de hauteur",
      "suffocation": "Suffocation",
      "void": "Vide",
      "pvp": "PvP",
      "lava": "Lave",
      "fire": "Feu",
      "unknown": "Inconnu"
    },
    "deathChat": {
      "pvp": "%V% a été tué par %A%",
      "suffocation": "%V% a suffoqué dans un mur",
      "void": "%V% est tombé hors du monde",
      "fall": "%V% est tombé d'une grande hauteur",
      "lava": "%V% est mort brûlé dans la lave",
      "fire": "%V% est mort brûlé"
    },
    "killDeathMsg": "Le joueur est mort",
    "killAllMsg": "[Serveur] : Tous les joueurs ont été tués",
    "srvUsageKillCmd": "Usage : /kill | /kill @p | /kill @a | /kill <nom>",
    "srvKillNoPlayer": "[Serveur] : Joueur introuvable : ",
    "srvCheatsOn": "[Serveur] : Triches activées !",
    "srvCheatsOff": "[Serveur] : Triches désactivées !",
    "srvUsageCheats": "Usage : /cheats on ou /cheats off",
    "srvCheatsHostOnly": "[Serveur] : Seul l'hôte peut modifier les triches !",
    "srvMpOnlyCmd": "[Serveur] : Cette commande est réservée au multijoueur",
    "srvCheatsSpOnly": "[Serveur] : Les triches se règlent depuis le menu !",
    "srvShoutNoPerm": "Cette commande est réservée au rang Twitch et supérieur",
    "srvUsageShout": "Usage : /shout <message>",
    "camFirstPerson": "🎥 Vue à la 1ère personne",
    "camThirdBack": "🎥 Vue à la 3e personne (arrière)",
    "camThirdFront": "🎥 Vue à la 3e personne (avant)",
    "skinTitle": "PARAMÈTRES DE SKIN",
    "skinPreview": "APERÇU",
    "skinUploader": "IMPORTATEUR DE SKIN",
    "skinUploadHint": "📁 Importer un PNG de skin Minecraft",
    "skinUploadSize": "64×64, 64×32 ou 128×128 pixels",
    "skinChoose": "📂 CHOISIR UN FICHIER",
    "skinReset": "🔄 RÉINITIALISER À STEVE",
    "skinMenuBtn": "🎨 SKIN PERSONNALISÉ",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Votre skin est visible par les autres joueurs en multijoueur.",
    "skinLoaded": "✅ Skin chargé !",
    "skinError": "❌ Erreur : doit être un PNG 64×64, 64×32 ou 128×128.",
    "skinGuestWarning": "🔒 Un compte est requis pour importer un skin personnalisé.",
    "skinGuestHint": "Connectez-vous au site si vous avez un compte.",
    "heightLimitMsg": "⛔ Limite de hauteur de construction atteinte ! (250 blocs)",
    "worldBorderMsg": "⛔ Vous avez atteint la limite du monde !",
    "giveUsage": "Usage : /give <cible> <bloc>",
    "giveUnknownBlock": "Bloc inconnu : ",
    "giveSuccess": "Donné : ",
    "giveNoTarget": "Cible introuvable : ",
    "helpTitle": "─── COMMANDES ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Changer de mode (creative/survival/adventure/spectator)",
      "/give <@p|@a|nom> <bloc>  →  Donner un bloc",
      "/kill [@p|@a|nom]  →  Tuer un joueur",
      "/op <nom>  →  Accorder opérateur",
      "/unop <nom>  →  Révoquer opérateur",
      "/kick <nom>  →  Expulser un joueur",
      "/ban <nom>  →  Bannir un joueur",
      "/unban <nom>  →  Débannir un joueur",
      "/setworldspawn  →  Définir le point d'apparition",
      "/setblock <x> <y> <z> <bloc>  →  Placer un bloc à une position",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <bloc>  →  Remplir une zone",
      "/summon <sheep|cow|pig> [x y z]  →  Faire apparaître une entité",
      "/friend <nom>  →  Demande d'ami",
      "/shout <message>  →  Message global",
      "/help  →  Afficher ce menu"
    ],
    "tmTitle": "PHASE DE TEST",
    "tmDesc": "Vous n'êtes pas connecté. Normalement, cette action nécessite un compte.<br><br>Le jeu étant en phase de <strong style=\"color:#ffc84a\">développement / test</strong>, vous pouvez continuer sans compte. Cependant cette version <strong style=\"color:#ff7a7a\">peut contenir des bugs et fonctionnalités manquantes</strong>, les données seront envoyées en tant qu'invité.",
    "tmContinue": "CONTINUER QUAND MÊME",
    "tmCancel": "ANNULER",
    "guestCreateTitle": "Un compte est requis pour créer un serveur.",
    "guestCreateHint": "Connectez-vous au site pour utiliser cette fonctionnalité.",
    "guestLoadMsg": "🔒 Un compte est requis pour charger un monde.",
    "guestCreateMsg": "🔒 Un compte est requis pour créer un serveur. Veuillez vous connecter.",
    "slTitle": "LISTE DES SERVEURS",
    "slSavedWorld": "CHOISIR UN MONDE SAUVEGARDÉ",
    "slNoBrowser": "Aucun monde sauvegardé trouvé dans le navigateur.",
    "slServerSettings": "PARAMÈTRES DU SERVEUR",
    "slLoadHost": "CHARGER ET HÉBERGER",
    "slWorldLoading": "Chargement du monde...",
    "slWorldReadError": "⚠ Impossible de lire les données du monde.",
    "slServerError": "⚠ Erreur du serveur : ",
    "slSearchPh": "Rechercher un serveur...",
    "slConnecting": "Chargement des serveurs...",
    "slNoResponse": "⚠ Aucune réponse du serveur.",
    "slNoServers": "Aucun serveur actif trouvé.",
    "slCreateServer": "⚙️ CRÉER UN SERVEUR",
    "msTitle": "⚙ GÉRER LE SERVEUR",
    "msTabPlayers": "👥 JOUEURS",
    "msTabAdmins": "🛡 ADMINS ET BANNIS",
    "msTabServer": "⚙ SERVEUR",
    "msBtnManage": "🛡 GÉRER LE SERVEUR",
    "msLblAdmins": "ADMINS",
    "msLblBanned": "BANNIS",
    "msLblAccess": "Accès",
    "msLblPvp": "PvP",
    "msLblCheats": "Triches",
    "msOptPublic": "🌐 Public",
    "msOptRegistered": "🔑 Inscrits uniquement",
    "msOptPrivate": "🔒 Privé",
    "msBtnPromote": "Promouvoir",
    "msBtnDemote": "Rétrograder",
    "msBtnKick": "Expulser",
    "msBtnBan": "Bannir",
    "msBtnUnban": "Débannir",
    "msBtnShutdown": "🛑 ARRÊTER LE SERVEUR",
    "msBtnClose": "← FERMER",
    "msNoPlayers": "Aucun joueur sur le serveur.",
    "msNoAdmins": "Aucun admin.",
    "msNoBanned": "Aucun joueur banni.",
    "msPvpOn": "ACTIVÉ",
    "msPvpOff": "DÉSACTIVÉ",
    "msCheatsOn": "ACTIVÉ",
    "msCheatsOff": "DÉSACTIVÉ",
    "hcModLabel": "MODE HARDCORE",
    "hcOn": "ACTIVÉ",
    "hcOff": "DÉSACTIVÉ",
    "hcWatchWorld": "Observer le monde",
    "hcMainMenu": "Retour au menu principal",
    "hcBlockedGeneric": "⛔ Les commandes sont bloquées en mode Hardcore.",
    "hcBlockedSpectator": "⛔ Bloqué en mode Hardcore.",
    "specModeSet": "Mode de jeu réglé sur Spectateur.",
    "hcWorldEnded": "💀 Ce monde Hardcore est terminé. Vous pouvez seulement observer.",
    "spStateRestored": "💾 État du monde restauré.",
    "spDeadTag": "☠ MORT",
    "spDeadTooltip": "S'ouvre en mode spectateur",
    "myWorldsTitle": "MES MONDES",
    "newWorldBtn": "➕ CRÉER UN NOUVEAU MONDE",
    "noWorldsYet": "Aucun monde sauvegardé pour l'instant.",
    "noWorldsHint": "Créez ou jouez à un nouveau monde.",
    "editWorldName": "NOM DU MONDE",
    "editWorldNamePh": "Nom du monde...",
    "editWorldType": "TYPE DE MONDE",
    "editGameMode": "MODE DE JEU",
    "editCheats": "TRICHES",
    "saveBtn": "💾 ENREGISTRER",
    "cancelBtn": "✖ ANNULER",
    "wtNormal": "NORMAL",
    "wtFlat": "PLAT",
    "wtSmall": "PETIT",
    "gmSurvival": "SURVIE",
    "gmCreative": "CRÉATIF",
    "gmAdventure": "AVENTURE",
    "chOff": "DÉSACTIVÉ",
    "chOn": "ACTIVÉ",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Bloc",
    "f3Chunk": "Chunk",
    "f3Facing": "Direction",
    "f3Pitch": "Inclinaison",
    "f3Biome": "Biome",
    "f3Targeted": "Ciblé",
    "f3World": "Monde",
    "f3Seed": "Seed",
    "f3Mode": "Mode",
    "f3Flying": "Vol",
    "f3Grounded": "Au sol",
    "f3Chunks": "Chunks",
    "controlsTabLabel": "Contrôles",
    "languageTabLabel": "Langue"
  },
  "es": {
    "title": "LEGENDS INDEV",
    "singleplayer": "UN JUGADOR",
    "multiplayer": "MULTIJUGADOR",
    "settings": "AJUSTES",
    "deviceTitle": "SELECCIONAR DISPOSITIVO",
    "pcBtn": "ORDENADOR",
    "mobileBtn": "MÓVIL",
    "worldTitle": "SELECCIONAR MUNDO",
    "wInfTitle": "MUNDO NORMAL",
    "wInfDesc": "Terreno de ruido Perlin",
    "wSmTitle": "MUNDO PEQUEÑO",
    "wSmDesc": "Ligero y rápido",
    "wFlatTitle": "MUNDO PLANO",
    "wFlatDesc": "Terreno completamente plano",
    "back": "← ATRÁS",
    "errTitle": "¡Error del motor gráfico!",
    "errDesc": "Comprueba tu conexión a internet.",
    "resume": "REANUDAR",
    "quit": "SALIR",
    "pauseTitle": "MENÚ DEL JUEGO",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "SALTAR",
    "mpTitle": "MULTIJUGADOR",
    "mpJoin": "UNIRSE",
    "mpHost": "ALOJAR",
    "settingsTitle": "AJUSTES",
    "joinTitle": "UNIRSE A SALA",
    "joinNamePh": "Tu nombre de jugador",
    "joinCodePh": "CÓDIGO DE 4 LETRAS",
    "joinBtn": "UNIRSE",
    "hostTitle": "ALOJAR SALA",
    "hostNamePh": "Tu nombre de jugador",
    "hostStart": "INICIAR SALA",
    "codeLabel": "CÓDIGO DE SALA",
    "wmcInf": "NORMAL",
    "wmcFlat": "PLANO",
    "wmcSm": "PEQUEÑO",
    "gmcSurv": "SUPERVIVENCIA",
    "gmcCrea": "CREATIVO",
    "gmcAdv": "AVENTURA",
    "chatHint": "⌨  Intro → Chat",
    "chatPh": "Escribe un mensaje...",
    "sysJoin": " se ha unido",
    "sysLeft": " se ha ido",
    "sysDisc": "Conexión perdida",
    "sysSpawnSet": "✅ ¡Punto de aparición del mundo actualizado!",
    "sysSpawnSetUsage": "Uso: /setworldspawn (debes ser el anfitrión)",
    "srvUsageSetblock": "Uso: /setblock <x> <y> <z> <bloque>",
    "srvSetblockSuccess": "✅ Bloque colocado en: ",
    "srvUsageFill": "Uso: /fill <x1> <y1> <z1> <x2> <y2> <z2> <bloque>",
    "srvFillSuccess": "✅ Zona rellenada, número de bloques: ",
    "srvFillTooLarge": "⚠️ Demasiados bloques (límite superado): ",
    "crosshairModeLabel": "🎯 Modo de mira",
    "crosshairModeSublabel": "(colocar bloque en el centro)",
    "srvSpawnCodeMissing": "⚠️ Código de sala no encontrado, no se pudo contactar con el servidor.",
    "srvSpawnNoConnection": "⚠️ No conectado al servidor.",
    "srvSpawnFailed": "⚠️ No se pudo establecer el punto de aparición: ",
    "sysPlayerSaved": "💾 Posición e inventario guardados.",
    "modeCreative": "Modo Creativo",
    "modeSurvival": "Modo Supervivencia",
    "modeAdventure": "Modo Aventura",
    "rdLabel": "Distancia de renderizado",
    "rdPcLabel": "Distancia de renderizado",
    "rdMLabel": "Distancia de renderizado",
    "spSurv": "SUPERVIVENCIA",
    "spCrea": "CREATIVO",
    "spAdv": "AVENTURA",
    "crouchBtn": "AGACHARSE",
    "worldSectionLabel": "MUNDO",
    "gameModeSectionLabel": "MODO DE JUEGO",
    "cheatsLabel": "TRUCOS",
    "cheatOff": "DESACTIVADO",
    "cheatOn": "ACTIVADO",
    "deathTitle": "¡Has muerto!",
    "respawnBtn": "Reaparecer",
    "pauseSettings": "AJUSTES",
    "mpBrowse": "EXPLORAR",
    "mpLoad": "CARGAR",
    "mpCreate": "CREAR",
    "mpServerList": "LISTA DE SERVIDORES",
    "invTitle": "INVENTARIO",
    "invBlocks": "BLOQUES",
    "invHint": "BARRA RÁPIDA – ELIGE UN BLOQUE Y HAZ CLIC EN UNA RANURA",
    "invClose": "[E] cerrar",
    "bkNames": [
      "Tablones",
      "Hierba",
      "Tierra",
      "Piedra",
      "Tronco",
      "Piedra rota",
      "Vidrio",
      "Hojas",
      "Arena",
      "Agua",
      "Roca madre",
      "Lava",
      "Obsidiana",
      "Andesita",
      "Granito",
      "Diorita",
      "Grava"
    ],
    "settingsPcBtn": "AJUSTES DE PC",
    "settingsMobileBtn": "AJUSTES MÓVILES",
    "pcSettingsTitle": "AJUSTES DE PC",
    "mobileSettingsTitle": "AJUSTES MÓVILES",
    "sensLabel": "Sensibilidad",
    "fovLabel": "Campo de visión (FOV)",
    "keybindsTitle": "ASIGNACIÓN DE TECLAS",
    "kbForward": "Adelante",
    "kbBack": "Atrás",
    "kbLeft": "Izquierda",
    "kbRight": "Derecha",
    "kbJump": "Saltar",
    "kbSlot": "Elegir ranura",
    "kbBreak": "Romper bloque",
    "kbPlace": "Colocar bloque",
    "kbChat": "Chat",
    "kbPause": "Pausa",
    "srvPrefix": "[Servidor]: ",
    "srvNoCheat": "[Servidor]: ¡Los trucos están desactivados!",
    "srvNoPerms": "[Servidor]: ¡No tienes permiso!",
    "srvHostOnly": "[Servidor]: ¡Solo el anfitrión!",
    "srvUsageMode": "Uso: /mode c, /mode s o /mode a",
    "srvUsageOp": "Uso: /op <nombre>",
    "srvUsageUnop": "Uso: /unop <nombre>",
    "srvUsageKick": "Uso: /kick <nombre>",
    "srvUsageBan": "Uso: /ban <nombre>",
    "srvNoPlayer": "[Servidor]: Jugador no encontrado: ",
    "srvNoCantKickOp": "[Servidor]: ¡No se puede expulsar a operadores!",
    "srvNoCantBanOp": "[Servidor]: ¡No se puede banear a operadores!",
    "srvUnknownCmd": "Comando desconocido: /",
    "srvUnknownEntity": "Entidad desconocida: ",
    "srvUsageSummon": "Uso: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "No se pudo invocar la entidad (chunk no cargado).",
    "srvSummonSuccess": "%e invocado en (%x, %y, %z)",
    "srvFriendUsage": "Uso: /friend <nombreJugador>",
    "srvFriendSent": "¡Solicitud de amistad enviada!",
    "srvFriendGuest": "¡No se puede enviar solicitud de amistad a jugadores no registrados!",
    "srvFriendSelf": "¡No puedes enviarte una solicitud de amistad a ti mismo!",
    "srvModeChanged": "Modo: ",
    "srvOpGranted": " ¡ahora es operador!",
    "srvOpRevoked": " ya no es operador.",
    "srvKicked": " fue expulsado.",
    "srvBanned": " fue baneado.",
    "srvUnbanned": " fue desbaneado.",
    "srvKickedBy": " te expulsó.",
    "srvOpBecame": " se convirtió en operador",
    "srvOpLost": " ya no es operador",
    "srvKickedNotice": "Fuiste eliminado del servidor: ",
    "banScreenTitle": "¡Has sido baneado de este servidor!",
    "kickScreenTitle": "¡Has sido expulsado del servidor!",
    "banByText": " ¡te ha baneado!",
    "kickByText": " ¡te ha expulsado!",
    "backToMenuBtn": "Volver al menú principal",
    "rateLimitMsg": "¡Estás enviando mensajes demasiado rápido!",
    "deathMessages": {
      "fall": "Caída alta",
      "suffocation": "Asfixia",
      "void": "Vacío",
      "pvp": "PvP",
      "lava": "Lava",
      "fire": "Fuego",
      "unknown": "Desconocido"
    },
    "deathChat": {
      "pvp": "%V% fue asesinado por %A%",
      "suffocation": "%V% se asfixió en una pared",
      "void": "%V% cayó fuera del mundo",
      "fall": "%V% cayó desde una gran altura",
      "lava": "%V% murió quemado en lava",
      "fire": "%V% murió quemado"
    },
    "killDeathMsg": "El jugador murió",
    "killAllMsg": "[Servidor]: Todos los jugadores fueron eliminados",
    "srvUsageKillCmd": "Uso: /kill | /kill @p | /kill @a | /kill <nombre>",
    "srvKillNoPlayer": "[Servidor]: Jugador no encontrado: ",
    "srvCheatsOn": "[Servidor]: ¡Trucos activados!",
    "srvCheatsOff": "[Servidor]: ¡Trucos desactivados!",
    "srvUsageCheats": "Uso: /cheats on o /cheats off",
    "srvCheatsHostOnly": "[Servidor]: ¡Solo el anfitrión puede cambiar los trucos!",
    "srvMpOnlyCmd": "[Servidor]: Este comando solo se puede usar en multijugador",
    "srvCheatsSpOnly": "[Servidor]: ¡Los trucos se activan desde el menú!",
    "srvShoutNoPerm": "Este comando es para rango Twitch o superior",
    "srvUsageShout": "Uso: /shout <mensaje>",
    "camFirstPerson": "🎥 Primera persona",
    "camThirdBack": "🎥 Tercera persona (atrás)",
    "camThirdFront": "🎥 Tercera persona (adelante)",
    "skinTitle": "AJUSTES DE SKIN",
    "skinPreview": "VISTA PREVIA",
    "skinUploader": "SUBIR SKIN",
    "skinUploadHint": "📁 Sube un PNG de skin de Minecraft",
    "skinUploadSize": "64×64, 64×32 o 128×128 píxeles",
    "skinChoose": "📂 ELEGIR ARCHIVO",
    "skinReset": "🔄 RESTABLECER A STEVE",
    "skinMenuBtn": "🎨 SKIN PERSONALIZADA",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Tu skin es visible para otros jugadores en multijugador.",
    "skinLoaded": "✅ ¡Skin cargada!",
    "skinError": "❌ Error: debe ser un PNG de 64×64, 64×32 o 128×128.",
    "skinGuestWarning": "🔒 Se requiere una cuenta para subir una skin personalizada.",
    "skinGuestHint": "Inicia sesión en el sitio si tienes una cuenta.",
    "heightLimitMsg": "⛔ ¡Se alcanzó el límite de altura de construcción! (250 bloques)",
    "worldBorderMsg": "⛔ ¡Has alcanzado el borde del mundo!",
    "giveUsage": "Uso: /give <objetivo> <bloque>",
    "giveUnknownBlock": "Bloque desconocido: ",
    "giveSuccess": "Entregado: ",
    "giveNoTarget": "Objetivo no encontrado: ",
    "helpTitle": "─── COMANDOS ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Cambiar modo (creative/survival/adventure/spectator)",
      "/give <@p|@a|nombre> <bloque>  →  Dar un bloque",
      "/kill [@p|@a|nombre]  →  Matar jugador",
      "/op <nombre>  →  Otorgar operador",
      "/unop <nombre>  →  Revocar operador",
      "/kick <nombre>  →  Expulsar jugador",
      "/ban <nombre>  →  Banear jugador",
      "/unban <nombre>  →  Desbanear jugador",
      "/setworldspawn  →  Establecer punto de aparición",
      "/setblock <x> <y> <z> <bloque>  →  Colocar bloque en posición",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <bloque>  →  Rellenar zona con bloque",
      "/summon <sheep|cow|pig> [x y z]  →  Invocar una entidad",
      "/friend <nombre>  →  Solicitud de amistad",
      "/shout <mensaje>  →  Mensaje global",
      "/help  →  Mostrar este menú"
    ],
    "tmTitle": "FASE DE PRUEBAS",
    "tmDesc": "No has iniciado sesión. En condiciones normales, esta acción requiere una cuenta.<br><br>Como el juego está en fase de <strong style=\"color:#ffc84a\">desarrollo/pruebas</strong>, puedes continuar sin cuenta. Sin embargo, esta versión <strong style=\"color:#ff7a7a\">puede contener errores y funciones faltantes</strong>, los datos se enviarán como invitado.",
    "tmContinue": "CONTINUAR DE TODOS MODOS",
    "tmCancel": "CANCELAR",
    "guestCreateTitle": "Se requiere una cuenta para crear un servidor.",
    "guestCreateHint": "Inicia sesión en el sitio para usar esta función.",
    "guestLoadMsg": "🔒 Se requiere una cuenta para cargar un mundo.",
    "guestCreateMsg": "🔒 Se requiere una cuenta para crear un servidor. Por favor, inicia sesión.",
    "slTitle": "LISTA DE SERVIDORES",
    "slSavedWorld": "SELECCIONAR MUNDO GUARDADO",
    "slNoBrowser": "No se encontraron mundos guardados en el navegador.",
    "slServerSettings": "AJUSTES DEL SERVIDOR",
    "slLoadHost": "CARGAR Y ALOJAR",
    "slWorldLoading": "Cargando mundo...",
    "slWorldReadError": "⚠ No se pudieron leer los datos del mundo.",
    "slServerError": "⚠ Error del servidor: ",
    "slSearchPh": "Buscar servidor...",
    "slConnecting": "Cargando servidores...",
    "slNoResponse": "⚠ Sin respuesta del servidor.",
    "slNoServers": "No se encontraron servidores activos.",
    "slCreateServer": "⚙️ CREAR SERVIDOR",
    "msTitle": "⚙ GESTIONAR SERVIDOR",
    "msTabPlayers": "👥 JUGADORES",
    "msTabAdmins": "🛡 ADMINS Y BANEADOS",
    "msTabServer": "⚙ SERVIDOR",
    "msBtnManage": "🛡 GESTIONAR SERVIDOR",
    "msLblAdmins": "ADMINS",
    "msLblBanned": "BANEADOS",
    "msLblAccess": "Acceso",
    "msLblPvp": "PvP",
    "msLblCheats": "Trucos",
    "msOptPublic": "🌐 Público",
    "msOptRegistered": "🔑 Solo registrados",
    "msOptPrivate": "🔒 Privado",
    "msBtnPromote": "Ascender",
    "msBtnDemote": "Degradar",
    "msBtnKick": "Expulsar",
    "msBtnBan": "Banear",
    "msBtnUnban": "Desbanear",
    "msBtnShutdown": "🛑 APAGAR SERVIDOR",
    "msBtnClose": "← CERRAR",
    "msNoPlayers": "No hay jugadores en el servidor.",
    "msNoAdmins": "Sin admins.",
    "msNoBanned": "Sin jugadores baneados.",
    "msPvpOn": "ACTIVADO",
    "msPvpOff": "DESACTIVADO",
    "msCheatsOn": "ACTIVADO",
    "msCheatsOff": "DESACTIVADO",
    "hcModLabel": "MODO HARDCORE",
    "hcOn": "ACTIVADO",
    "hcOff": "DESACTIVADO",
    "hcWatchWorld": "Ver el mundo",
    "hcMainMenu": "Volver al menú principal",
    "hcBlockedGeneric": "⛔ Los comandos están bloqueados en modo Hardcore.",
    "hcBlockedSpectator": "⛔ Bloqueado en modo Hardcore.",
    "specModeSet": "Modo de juego cambiado a Espectador.",
    "hcWorldEnded": "💀 Este mundo Hardcore ha terminado. Solo puedes observar.",
    "spStateRestored": "💾 Estado del mundo restaurado.",
    "spDeadTag": "☠ MUERTO",
    "spDeadTooltip": "Se abre en modo espectador",
    "myWorldsTitle": "MIS MUNDOS",
    "newWorldBtn": "➕ CREAR NUEVO MUNDO",
    "noWorldsYet": "Aún no hay mundos guardados.",
    "noWorldsHint": "Crea o juega un nuevo mundo.",
    "editWorldName": "NOMBRE DEL MUNDO",
    "editWorldNamePh": "Nombre del mundo...",
    "editWorldType": "TIPO DE MUNDO",
    "editGameMode": "MODO DE JUEGO",
    "editCheats": "TRUCOS",
    "saveBtn": "💾 GUARDAR",
    "cancelBtn": "✖ CANCELAR",
    "wtNormal": "NORMAL",
    "wtFlat": "PLANO",
    "wtSmall": "PEQUEÑO",
    "gmSurvival": "SUPERVIVENCIA",
    "gmCreative": "CREATIVO",
    "gmAdventure": "AVENTURA",
    "chOff": "DESACTIVADO",
    "chOn": "ACTIVADO",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Bloque",
    "f3Chunk": "Chunk",
    "f3Facing": "Orientación",
    "f3Pitch": "Inclinación",
    "f3Biome": "Bioma",
    "f3Targeted": "Apuntado",
    "f3World": "Mundo",
    "f3Seed": "Semilla",
    "f3Mode": "Modo",
    "f3Flying": "Volando",
    "f3Grounded": "En el suelo",
    "f3Chunks": "Chunks",
    "controlsTabLabel": "Controles",
    "languageTabLabel": "Idioma"
  },
  "ru": {
    "title": "LEGENDS INDEV",
    "singleplayer": "ОДИН ИГРОК",
    "multiplayer": "МУЛЬТИПЛЕЕР",
    "settings": "НАСТРОЙКИ",
    "deviceTitle": "ВЫБОР УСТРОЙСТВА",
    "pcBtn": "КОМПЬЮТЕР",
    "mobileBtn": "МОБИЛЬНЫЙ",
    "worldTitle": "ВЫБОР МИРА",
    "wInfTitle": "ОБЫЧНЫЙ МИР",
    "wInfDesc": "Рельеф на основе шума Перлина",
    "wSmTitle": "МАЛЫЙ МИР",
    "wSmDesc": "Лёгкий и быстрый",
    "wFlatTitle": "ПЛОСКИЙ МИР",
    "wFlatDesc": "Полностью плоская местность",
    "back": "← НАЗАД",
    "errTitle": "Ошибка графического движка!",
    "errDesc": "Проверьте подключение к интернету.",
    "resume": "ПРОДОЛЖИТЬ",
    "quit": "ВЫЙТИ",
    "pauseTitle": "МЕНЮ ИГРЫ",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "ПРЫЖОК",
    "mpTitle": "МУЛЬТИПЛЕЕР",
    "mpJoin": "ПРИСОЕДИНИТЬСЯ",
    "mpHost": "СОЗДАТЬ",
    "settingsTitle": "НАСТРОЙКИ",
    "joinTitle": "ВОЙТИ В КОМНАТУ",
    "joinNamePh": "Ваше имя игрока",
    "joinCodePh": "КОД ИЗ 4 БУКВ",
    "joinBtn": "ВОЙТИ",
    "hostTitle": "СОЗДАТЬ КОМНАТУ",
    "hostNamePh": "Ваше имя игрока",
    "hostStart": "ЗАПУСТИТЬ КОМНАТУ",
    "codeLabel": "КОД КОМНАТЫ",
    "wmcInf": "ОБЫЧНЫЙ",
    "wmcFlat": "ПЛОСКИЙ",
    "wmcSm": "МАЛЫЙ",
    "gmcSurv": "ВЫЖИВАНИЕ",
    "gmcCrea": "ТВОРЧЕСТВО",
    "gmcAdv": "ПРИКЛЮЧЕНИЕ",
    "chatHint": "⌨  Enter → Чат",
    "chatPh": "Введите сообщение...",
    "sysJoin": " присоединился(-ась)",
    "sysLeft": " вышел(-ла)",
    "sysDisc": "Соединение потеряно",
    "sysSpawnSet": "✅ Точка возрождения мира обновлена!",
    "sysSpawnSetUsage": "Использование: /setworldspawn (нужно быть хостом)",
    "srvUsageSetblock": "Использование: /setblock <x> <y> <z> <блок>",
    "srvSetblockSuccess": "✅ Блок установлен: ",
    "srvUsageFill": "Использование: /fill <x1> <y1> <z1> <x2> <y2> <z2> <блок>",
    "srvFillSuccess": "✅ Область заполнена, количество блоков: ",
    "srvFillTooLarge": "⚠️ Слишком много блоков (превышен лимит): ",
    "crosshairModeLabel": "🎯 Режим прицела",
    "crosshairModeSublabel": "(размещать блок по центру)",
    "srvSpawnCodeMissing": "⚠️ Код комнаты не найден, сервер недоступен.",
    "srvSpawnNoConnection": "⚠️ Нет подключения к серверу.",
    "srvSpawnFailed": "⚠️ Не удалось установить точку возрождения: ",
    "sysPlayerSaved": "💾 Позиция и инвентарь сохранены.",
    "modeCreative": "Творческий режим",
    "modeSurvival": "Режим выживания",
    "modeAdventure": "Режим приключений",
    "rdLabel": "Дальность прорисовки",
    "rdPcLabel": "Дальность прорисовки",
    "rdMLabel": "Дальность прорисовки",
    "spSurv": "ВЫЖИВАНИЕ",
    "spCrea": "ТВОРЧЕСТВО",
    "spAdv": "ПРИКЛЮЧЕНИЕ",
    "crouchBtn": "ПРИСЕСТЬ",
    "worldSectionLabel": "МИР",
    "gameModeSectionLabel": "РЕЖИМ ИГРЫ",
    "cheatsLabel": "ЧИТЫ",
    "cheatOff": "ВЫКЛ",
    "cheatOn": "ВКЛ",
    "deathTitle": "Вы погибли!",
    "respawnBtn": "Возродиться",
    "pauseSettings": "НАСТРОЙКИ",
    "mpBrowse": "ОБЗОР",
    "mpLoad": "ЗАГРУЗИТЬ",
    "mpCreate": "СОЗДАТЬ",
    "mpServerList": "СПИСОК СЕРВЕРОВ",
    "invTitle": "ИНВЕНТАРЬ",
    "invBlocks": "БЛОКИ",
    "invHint": "ПАНЕЛЬ БЫСТРОГО ДОСТУПА – ВЫБЕРИТЕ БЛОК, ЗАТЕМ НАЖМИТЕ НА ЯЧЕЙКУ",
    "invClose": "[E] закрыть",
    "bkNames": [
      "Доски",
      "Трава",
      "Земля",
      "Камень",
      "Бревно",
      "Булыжник",
      "Стекло",
      "Листва",
      "Песок",
      "Вода",
      "Бедрок",
      "Лава",
      "Обсидиан",
      "Андезит",
      "Гранит",
      "Диорит",
      "Гравий"
    ],
    "settingsPcBtn": "НАСТРОЙКИ ПК",
    "settingsMobileBtn": "МОБИЛЬНЫЕ НАСТРОЙКИ",
    "pcSettingsTitle": "НАСТРОЙКИ ПК",
    "mobileSettingsTitle": "МОБИЛЬНЫЕ НАСТРОЙКИ",
    "sensLabel": "Чувствительность",
    "fovLabel": "Угол обзора (FOV)",
    "keybindsTitle": "НАЗНАЧЕНИЕ КЛАВИШ",
    "kbForward": "Вперёд",
    "kbBack": "Назад",
    "kbLeft": "Влево",
    "kbRight": "Вправо",
    "kbJump": "Прыжок",
    "kbSlot": "Выбор ячейки",
    "kbBreak": "Сломать блок",
    "kbPlace": "Поставить блок",
    "kbChat": "Чат",
    "kbPause": "Пауза",
    "srvPrefix": "[Сервер]: ",
    "srvNoCheat": "[Сервер]: Читы отключены!",
    "srvNoPerms": "[Сервер]: У вас нет прав!",
    "srvHostOnly": "[Сервер]: Только для хоста!",
    "srvUsageMode": "Использование: /mode c, /mode s или /mode a",
    "srvUsageOp": "Использование: /op <имя>",
    "srvUsageUnop": "Использование: /unop <имя>",
    "srvUsageKick": "Использование: /kick <имя>",
    "srvUsageBan": "Использование: /ban <имя>",
    "srvNoPlayer": "[Сервер]: Игрок не найден: ",
    "srvNoCantKickOp": "[Сервер]: Нельзя кикнуть оператора!",
    "srvNoCantBanOp": "[Сервер]: Нельзя забанить оператора!",
    "srvUnknownCmd": "Неизвестная команда: /",
    "srvUnknownEntity": "Неизвестная сущность: ",
    "srvUsageSummon": "Использование: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Не удалось создать сущность (чанк не загружен).",
    "srvSummonSuccess": "%e создан в (%x, %y, %z)",
    "srvFriendUsage": "Использование: /friend <имяИгрока>",
    "srvFriendSent": "Запрос в друзья отправлен!",
    "srvFriendGuest": "Нельзя отправить запрос в друзья незарегистрированному игроку!",
    "srvFriendSelf": "Вы не можете отправить запрос в друзья самому себе!",
    "srvModeChanged": "Режим: ",
    "srvOpGranted": " теперь оператор!",
    "srvOpRevoked": " больше не оператор.",
    "srvKicked": " был кикнут.",
    "srvBanned": " был забанен.",
    "srvUnbanned": " разбанен.",
    "srvKickedBy": " кикнул(-а) вас.",
    "srvOpBecame": " стал оператором",
    "srvOpLost": " больше не оператор",
    "srvKickedNotice": "Вы были удалены с сервера: ",
    "banScreenTitle": "Вы забанены на этом сервере!",
    "kickScreenTitle": "Вы были кикнуты с сервера!",
    "banByText": " забанил(-а) вас!",
    "kickByText": " кикнул(-а) вас!",
    "backToMenuBtn": "Вернуться в главное меню",
    "rateLimitMsg": "Вы отправляете сообщения слишком быстро!",
    "deathMessages": {
      "fall": "Падение с высоты",
      "suffocation": "Удушье",
      "void": "Пустота",
      "pvp": "PvP",
      "lava": "Лава",
      "fire": "Огонь",
      "unknown": "Неизвестно"
    },
    "deathChat": {
      "pvp": "%V% был убит игроком %A%",
      "suffocation": "%V% задохнулся в стене",
      "void": "%V% выпал из мира",
      "fall": "%V% упал с большой высоты",
      "lava": "%V% сгорел в лаве",
      "fire": "%V% сгорел"
    },
    "killDeathMsg": "Игрок погиб",
    "killAllMsg": "[Сервер]: Все игроки были убиты",
    "srvUsageKillCmd": "Использование: /kill | /kill @p | /kill @a | /kill <имя>",
    "srvKillNoPlayer": "[Сервер]: Игрок не найден: ",
    "srvCheatsOn": "[Сервер]: Читы включены!",
    "srvCheatsOff": "[Сервер]: Читы отключены!",
    "srvUsageCheats": "Использование: /cheats on или /cheats off",
    "srvCheatsHostOnly": "[Сервер]: Только хост может менять читы!",
    "srvMpOnlyCmd": "[Сервер]: Эту команду можно использовать только в мультиплеере",
    "srvCheatsSpOnly": "[Сервер]: Читы переключаются из меню!",
    "srvShoutNoPerm": "Эта команда доступна для ранга Twitch и выше",
    "srvUsageShout": "Использование: /shout <сообщение>",
    "camFirstPerson": "🎥 От первого лица",
    "camThirdBack": "🎥 От третьего лица (сзади)",
    "camThirdFront": "🎥 От третьего лица (спереди)",
    "skinTitle": "НАСТРОЙКИ СКИНА",
    "skinPreview": "ПРЕДПРОСМОТР",
    "skinUploader": "ЗАГРУЗКА СКИНА",
    "skinUploadHint": "📁 Загрузить PNG скина Minecraft",
    "skinUploadSize": "64×64, 64×32 или 128×128 пикселей",
    "skinChoose": "📂 ВЫБРАТЬ ФАЙЛ",
    "skinReset": "🔄 СБРОСИТЬ НА STEVE",
    "skinMenuBtn": "🎨 СВОЙ СКИН",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Ваш скин виден другим игрокам в мультиплеере.",
    "skinLoaded": "✅ Скин загружен!",
    "skinError": "❌ Ошибка: файл должен быть PNG 64×64, 64×32 или 128×128.",
    "skinGuestWarning": "🔒 Для загрузки своего скина требуется аккаунт.",
    "skinGuestHint": "Войдите на сайт, если у вас есть аккаунт.",
    "heightLimitMsg": "⛔ Достигнут лимит высоты постройки! (250 блоков)",
    "worldBorderMsg": "⛔ Вы достигли границы мира!",
    "giveUsage": "Использование: /give <цель> <блок>",
    "giveUnknownBlock": "Неизвестный блок: ",
    "giveSuccess": "Выдано: ",
    "giveNoTarget": "Цель не найдена: ",
    "helpTitle": "─── КОМАНДЫ ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Сменить режим (creative/survival/adventure/spectator)",
      "/give <@p|@a|имя> <блок>  →  Выдать блок",
      "/kill [@p|@a|имя]  →  Убить игрока",
      "/op <имя>  →  Выдать оператора",
      "/unop <имя>  →  Снять оператора",
      "/kick <имя>  →  Кикнуть игрока",
      "/ban <имя>  →  Забанить игрока",
      "/unban <имя>  →  Разбанить игрока",
      "/setworldspawn  →  Установить точку возрождения",
      "/setblock <x> <y> <z> <блок>  →  Поставить блок в позиции",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <блок>  →  Заполнить область блоком",
      "/summon <sheep|cow|pig> [x y z]  →  Создать сущность",
      "/friend <имя>  →  Запрос в друзья",
      "/shout <сообщение>  →  Глобальное сообщение",
      "/help  →  Показать это меню"
    ],
    "tmTitle": "ТЕСТОВЫЙ ЭТАП",
    "tmDesc": "Вы не вошли в аккаунт. Обычно для этого действия требуется аккаунт.<br><br>Поскольку игра находится на этапе <strong style=\"color:#ffc84a\">разработки/тестирования</strong>, вы можете продолжить без аккаунта. Однако эта версия <strong style=\"color:#ff7a7a\">может содержать ошибки и отсутствующие функции</strong>, данные будут отправлены как гость.",
    "tmContinue": "ВСЁ РАВНО ПРОДОЛЖИТЬ",
    "tmCancel": "ОТМЕНА",
    "guestCreateTitle": "Для создания сервера требуется аккаунт.",
    "guestCreateHint": "Войдите на сайт, чтобы использовать эту функцию.",
    "guestLoadMsg": "🔒 Для загрузки мира требуется аккаунт.",
    "guestCreateMsg": "🔒 Для создания сервера требуется аккаунт. Пожалуйста, войдите.",
    "slTitle": "СПИСОК СЕРВЕРОВ",
    "slSavedWorld": "ВЫБРАТЬ СОХРАНЁННЫЙ МИР",
    "slNoBrowser": "Сохранённые миры в браузере не найдены.",
    "slServerSettings": "НАСТРОЙКИ СЕРВЕРА",
    "slLoadHost": "ЗАГРУЗИТЬ И ЗАПУСТИТЬ",
    "slWorldLoading": "Загрузка мира...",
    "slWorldReadError": "⚠ Не удалось прочитать данные мира.",
    "slServerError": "⚠ Ошибка сервера: ",
    "slSearchPh": "Поиск сервера...",
    "slConnecting": "Загрузка серверов...",
    "slNoResponse": "⚠ Нет ответа от сервера.",
    "slNoServers": "Активные серверы не найдены.",
    "slCreateServer": "⚙️ СОЗДАТЬ СЕРВЕР",
    "msTitle": "⚙ УПРАВЛЕНИЕ СЕРВЕРОМ",
    "msTabPlayers": "👥 ИГРОКИ",
    "msTabAdmins": "🛡 АДМИНЫ И БАНЫ",
    "msTabServer": "⚙ СЕРВЕР",
    "msBtnManage": "🛡 УПРАВЛЕНИЕ СЕРВЕРОМ",
    "msLblAdmins": "АДМИНЫ",
    "msLblBanned": "ЗАБАНЕННЫЕ",
    "msLblAccess": "Доступ",
    "msLblPvp": "PvP",
    "msLblCheats": "Читы",
    "msOptPublic": "🌐 Публичный",
    "msOptRegistered": "🔑 Только зарегистрированные",
    "msOptPrivate": "🔒 Приватный",
    "msBtnPromote": "Повысить",
    "msBtnDemote": "Понизить",
    "msBtnKick": "Кикнуть",
    "msBtnBan": "Забанить",
    "msBtnUnban": "Разбанить",
    "msBtnShutdown": "🛑 ВЫКЛЮЧИТЬ СЕРВЕР",
    "msBtnClose": "← ЗАКРЫТЬ",
    "msNoPlayers": "На сервере нет игроков.",
    "msNoAdmins": "Нет админов.",
    "msNoBanned": "Нет забаненных игроков.",
    "msPvpOn": "ВКЛ",
    "msPvpOff": "ВЫКЛ",
    "msCheatsOn": "ВКЛ",
    "msCheatsOff": "ВЫКЛ",
    "hcModLabel": "ХАРДКОР РЕЖИМ",
    "hcOn": "ВКЛ",
    "hcOff": "ВЫКЛ",
    "hcWatchWorld": "Наблюдать за миром",
    "hcMainMenu": "Вернуться в главное меню",
    "hcBlockedGeneric": "⛔ Команды заблокированы в режиме Хардкор.",
    "hcBlockedSpectator": "⛔ Заблокировано в режиме Хардкор.",
    "specModeSet": "Режим игры изменён на Наблюдатель.",
    "hcWorldEnded": "💀 Этот Хардкор-мир завершён. Вы можете только наблюдать.",
    "spStateRestored": "💾 Состояние мира восстановлено.",
    "spDeadTag": "☠ МЁРТВ",
    "spDeadTooltip": "Открывается в режиме наблюдателя",
    "myWorldsTitle": "МОИ МИРЫ",
    "newWorldBtn": "➕ СОЗДАТЬ НОВЫЙ МИР",
    "noWorldsYet": "Пока нет сохранённых миров.",
    "noWorldsHint": "Создайте или сыграйте в новый мир.",
    "editWorldName": "НАЗВАНИЕ МИРА",
    "editWorldNamePh": "Название мира...",
    "editWorldType": "ТИП МИРА",
    "editGameMode": "РЕЖИМ ИГРЫ",
    "editCheats": "ЧИТЫ",
    "saveBtn": "💾 СОХРАНИТЬ",
    "cancelBtn": "✖ ОТМЕНА",
    "wtNormal": "ОБЫЧНЫЙ",
    "wtFlat": "ПЛОСКИЙ",
    "wtSmall": "МАЛЫЙ",
    "gmSurvival": "ВЫЖИВАНИЕ",
    "gmCreative": "ТВОРЧЕСТВО",
    "gmAdventure": "ПРИКЛЮЧЕНИЕ",
    "chOff": "ВЫКЛ",
    "chOn": "ВКЛ",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Блок",
    "f3Chunk": "Чанк",
    "f3Facing": "Направление",
    "f3Pitch": "Наклон",
    "f3Biome": "Биом",
    "f3Targeted": "Цель",
    "f3World": "Мир",
    "f3Seed": "Сид",
    "f3Mode": "Режим",
    "f3Flying": "Полёт",
    "f3Grounded": "На земле",
    "f3Chunks": "Чанки",
    "controlsTabLabel": "Управление",
    "languageTabLabel": "Язык"
  },
  "pt": {
    "title": "LEGENDS INDEV",
    "singleplayer": "UM JOGADOR",
    "multiplayer": "MULTIJOGADOR",
    "settings": "CONFIGURAÇÕES",
    "deviceTitle": "SELECIONAR DISPOSITIVO",
    "pcBtn": "COMPUTADOR",
    "mobileBtn": "CELULAR",
    "worldTitle": "SELECIONAR MUNDO",
    "wInfTitle": "MUNDO NORMAL",
    "wInfDesc": "Terreno com ruído Perlin",
    "wSmTitle": "MUNDO PEQUENO",
    "wSmDesc": "Leve e rápido",
    "wFlatTitle": "MUNDO PLANO",
    "wFlatDesc": "Terreno completamente plano",
    "back": "← VOLTAR",
    "errTitle": "Erro do motor gráfico!",
    "errDesc": "Verifique sua conexão com a internet.",
    "resume": "CONTINUAR",
    "quit": "SAIR",
    "pauseTitle": "MENU DO JOGO",
    "gameTitle": "Legends Indev v1.6.2",
    "jumpBtn": "PULAR",
    "mpTitle": "MULTIJOGADOR",
    "mpJoin": "ENTRAR",
    "mpHost": "HOSPEDAR",
    "settingsTitle": "CONFIGURAÇÕES",
    "joinTitle": "ENTRAR NA SALA",
    "joinNamePh": "Seu nome de jogador",
    "joinCodePh": "CÓDIGO DE 4 LETRAS",
    "joinBtn": "ENTRAR",
    "hostTitle": "HOSPEDAR SALA",
    "hostNamePh": "Seu nome de jogador",
    "hostStart": "INICIAR SALA",
    "codeLabel": "CÓDIGO DA SALA",
    "wmcInf": "NORMAL",
    "wmcFlat": "PLANO",
    "wmcSm": "PEQUENO",
    "gmcSurv": "SOBREVIVÊNCIA",
    "gmcCrea": "CRIATIVO",
    "gmcAdv": "AVENTURA",
    "chatHint": "⌨  Enter → Chat",
    "chatPh": "Digite uma mensagem...",
    "sysJoin": " entrou",
    "sysLeft": " saiu",
    "sysDisc": "Conexão perdida",
    "sysSpawnSet": "✅ Ponto de spawn do mundo atualizado!",
    "sysSpawnSetUsage": "Uso: /setworldspawn (precisa ser o host)",
    "srvUsageSetblock": "Uso: /setblock <x> <y> <z> <bloco>",
    "srvSetblockSuccess": "✅ Bloco colocado em: ",
    "srvUsageFill": "Uso: /fill <x1> <y1> <z1> <x2> <y2> <z2> <bloco>",
    "srvFillSuccess": "✅ Área preenchida, quantidade de blocos: ",
    "srvFillTooLarge": "⚠️ Muitos blocos (limite excedido): ",
    "crosshairModeLabel": "🎯 Modo de Mira",
    "crosshairModeSublabel": "(colocar bloco no centro)",
    "srvSpawnCodeMissing": "⚠️ Código da sala não encontrado, não foi possível contatar o servidor.",
    "srvSpawnNoConnection": "⚠️ Não conectado ao servidor.",
    "srvSpawnFailed": "⚠️ Não foi possível definir o ponto de spawn: ",
    "sysPlayerSaved": "💾 Posição e inventário salvos.",
    "modeCreative": "Modo Criativo",
    "modeSurvival": "Modo Sobrevivência",
    "modeAdventure": "Modo Aventura",
    "rdLabel": "Distância de Renderização",
    "rdPcLabel": "Distância de Renderização",
    "rdMLabel": "Distância de Renderização",
    "spSurv": "SOBREVIVÊNCIA",
    "spCrea": "CRIATIVO",
    "spAdv": "AVENTURA",
    "crouchBtn": "AGACHAR",
    "worldSectionLabel": "MUNDO",
    "gameModeSectionLabel": "MODO DE JOGO",
    "cheatsLabel": "TRAPAÇAS",
    "cheatOff": "DESATIVADO",
    "cheatOn": "ATIVADO",
    "deathTitle": "Você morreu!",
    "respawnBtn": "Renascer",
    "pauseSettings": "CONFIGURAÇÕES",
    "mpBrowse": "PROCURAR",
    "mpLoad": "CARREGAR",
    "mpCreate": "CRIAR",
    "mpServerList": "LISTA DE SERVIDORES",
    "invTitle": "INVENTÁRIO",
    "invBlocks": "BLOCOS",
    "invHint": "BARRA DE ATALHOS – ESCOLHA UM BLOCO E CLIQUE EM UM SLOT",
    "invClose": "[E] fechar",
    "bkNames": [
      "Tábuas",
      "Grama",
      "Terra",
      "Pedra",
      "Tora",
      "Pedregulho",
      "Vidro",
      "Folhas",
      "Areia",
      "Água",
      "Rocha-mãe",
      "Lava",
      "Obsidiana",
      "Andesito",
      "Granito",
      "Diorito",
      "Cascalho"
    ],
    "settingsPcBtn": "CONFIGURAÇÕES DE PC",
    "settingsMobileBtn": "CONFIGURAÇÕES MÓVEIS",
    "pcSettingsTitle": "CONFIGURAÇÕES DE PC",
    "mobileSettingsTitle": "CONFIGURAÇÕES MÓVEIS",
    "sensLabel": "Sensibilidade",
    "fovLabel": "Campo de Visão (FOV)",
    "keybindsTitle": "TECLAS DE ATALHO",
    "kbForward": "Frente",
    "kbBack": "Trás",
    "kbLeft": "Esquerda",
    "kbRight": "Direita",
    "kbJump": "Pular",
    "kbSlot": "Selecionar Slot",
    "kbBreak": "Quebrar Bloco",
    "kbPlace": "Colocar Bloco",
    "kbChat": "Chat",
    "kbPause": "Pausar",
    "srvPrefix": "[Servidor]: ",
    "srvNoCheat": "[Servidor]: As trapaças estão desativadas!",
    "srvNoPerms": "[Servidor]: Você não tem permissão!",
    "srvHostOnly": "[Servidor]: Apenas o host!",
    "srvUsageMode": "Uso: /mode c, /mode s ou /mode a",
    "srvUsageOp": "Uso: /op <nome>",
    "srvUsageUnop": "Uso: /unop <nome>",
    "srvUsageKick": "Uso: /kick <nome>",
    "srvUsageBan": "Uso: /ban <nome>",
    "srvNoPlayer": "[Servidor]: Jogador não encontrado: ",
    "srvNoCantKickOp": "[Servidor]: Não é possível expulsar operadores!",
    "srvNoCantBanOp": "[Servidor]: Não é possível banir operadores!",
    "srvUnknownCmd": "Comando desconhecido: /",
    "srvUnknownEntity": "Entidade desconhecida: ",
    "srvUsageSummon": "Uso: /summon <sheep|cow|pig> [x y z]",
    "srvSummonFail": "Não foi possível gerar a entidade (chunk não carregado).",
    "srvSummonSuccess": "%e gerado em (%x, %y, %z)",
    "srvFriendUsage": "Uso: /friend <nomeJogador>",
    "srvFriendSent": "Solicitação de amizade enviada!",
    "srvFriendGuest": "Não é possível enviar solicitação de amizade a jogadores não registrados!",
    "srvFriendSelf": "Você não pode enviar uma solicitação de amizade para si mesmo!",
    "srvModeChanged": "Modo: ",
    "srvOpGranted": " agora é operador!",
    "srvOpRevoked": " não é mais operador.",
    "srvKicked": " foi expulso.",
    "srvBanned": " foi banido.",
    "srvUnbanned": " foi desbanido.",
    "srvKickedBy": " expulsou você.",
    "srvOpBecame": " se tornou operador",
    "srvOpLost": " não é mais operador",
    "srvKickedNotice": "Você foi removido do servidor: ",
    "banScreenTitle": "Você foi banido deste servidor!",
    "kickScreenTitle": "Você foi expulso do servidor!",
    "banByText": " baniu você!",
    "kickByText": " expulsou você!",
    "backToMenuBtn": "Voltar ao Menu Principal",
    "rateLimitMsg": "Você está enviando mensagens muito rápido!",
    "deathMessages": {
      "fall": "Queda alta",
      "suffocation": "Sufocamento",
      "void": "Vazio",
      "pvp": "PvP",
      "lava": "Lava",
      "fire": "Fogo",
      "unknown": "Desconhecido"
    },
    "deathChat": {
      "pvp": "%V% foi morto por %A%",
      "suffocation": "%V% sufocou em uma parede",
      "void": "%V% caiu para fora do mundo",
      "fall": "%V% caiu de um lugar alto",
      "lava": "%V% morreu queimado em lava",
      "fire": "%V% morreu queimado"
    },
    "killDeathMsg": "Jogador morreu",
    "killAllMsg": "[Servidor]: Todos os jogadores foram mortos",
    "srvUsageKillCmd": "Uso: /kill | /kill @p | /kill @a | /kill <nome>",
    "srvKillNoPlayer": "[Servidor]: Jogador não encontrado: ",
    "srvCheatsOn": "[Servidor]: Trapaças ativadas!",
    "srvCheatsOff": "[Servidor]: Trapaças desativadas!",
    "srvUsageCheats": "Uso: /cheats on ou /cheats off",
    "srvCheatsHostOnly": "[Servidor]: Apenas o host pode alterar as trapaças!",
    "srvMpOnlyCmd": "[Servidor]: Este comando só pode ser usado no multijogador",
    "srvCheatsSpOnly": "[Servidor]: As trapaças podem ser ativadas pelo menu!",
    "srvShoutNoPerm": "Este comando é para rank Twitch ou superior",
    "srvUsageShout": "Uso: /shout <mensagem>",
    "camFirstPerson": "🎥 Primeira Pessoa",
    "camThirdBack": "🎥 Terceira Pessoa (Trás)",
    "camThirdFront": "🎥 Terceira Pessoa (Frente)",
    "skinTitle": "CONFIGURAÇÕES DE SKIN",
    "skinPreview": "PRÉ-VISUALIZAÇÃO",
    "skinUploader": "ENVIAR SKIN",
    "skinUploadHint": "📁 Enviar PNG de skin do Minecraft",
    "skinUploadSize": "64×64, 64×32 ou 128×128 pixels",
    "skinChoose": "📂 ESCOLHER ARQUIVO",
    "skinReset": "🔄 REDEFINIR PARA STEVE",
    "skinMenuBtn": "🎨 SKIN PERSONALIZADA",
    "skinSteve": "👦 STEVE",
    "skinAlex": "👩 ALEX",
    "skinNote": "Sua skin fica visível para outros jogadores no multijogador.",
    "skinLoaded": "✅ Skin carregada!",
    "skinError": "❌ Erro: deve ser um PNG de 64×64, 64×32 ou 128×128.",
    "skinGuestWarning": "🔒 É necessária uma conta para enviar uma skin personalizada.",
    "skinGuestHint": "Faça login no site se você tiver uma conta.",
    "heightLimitMsg": "⛔ Limite de altura de construção atingido! (250 blocos)",
    "worldBorderMsg": "⛔ Você atingiu a borda do mundo!",
    "giveUsage": "Uso: /give <alvo> <bloco>",
    "giveUnknownBlock": "Bloco desconhecido: ",
    "giveSuccess": "Dado: ",
    "giveNoTarget": "Alvo não encontrado: ",
    "helpTitle": "─── COMANDOS ───",
    "helpLines": [
      "/mode c|s|a|sp  →  Mudar modo (creative/survival/adventure/spectator)",
      "/give <@p|@a|nome> <bloco>  →  Dar um bloco",
      "/kill [@p|@a|nome]  →  Matar jogador",
      "/op <nome>  →  Conceder operador",
      "/unop <nome>  →  Revogar operador",
      "/kick <nome>  →  Expulsar jogador",
      "/ban <nome>  →  Banir jogador",
      "/unban <nome>  →  Desbanir jogador",
      "/setworldspawn  →  Definir ponto de spawn do mundo",
      "/setblock <x> <y> <z> <bloco>  →  Colocar bloco na posição",
      "/fill <x1> <y1> <z1> <x2> <y2> <z2> <bloco>  →  Preencher área com bloco",
      "/summon <sheep|cow|pig> [x y z]  →  Gerar uma entidade",
      "/friend <nome>  →  Solicitação de amizade",
      "/shout <mensagem>  →  Mensagem global",
      "/help  →  Mostrar este menu"
    ],
    "tmTitle": "FASE DE TESTES",
    "tmDesc": "Você não está conectado. Em condições normais, esta ação requer uma conta.<br><br>Como o jogo está em fase de <strong style=\"color:#ffc84a\">Desenvolvimento/Testes</strong>, você pode continuar sem uma conta. No entanto, esta versão <strong style=\"color:#ff7a7a\">pode conter erros e recursos ausentes</strong>, os dados serão enviados como convidado.",
    "tmContinue": "CONTINUAR MESMO ASSIM",
    "tmCancel": "CANCELAR",
    "guestCreateTitle": "É necessária uma conta para criar um servidor.",
    "guestCreateHint": "Faça login no site para usar este recurso.",
    "guestLoadMsg": "🔒 É necessária uma conta para carregar um mundo.",
    "guestCreateMsg": "🔒 É necessária uma conta para criar um servidor. Por favor, faça login.",
    "slTitle": "LISTA DE SERVIDORES",
    "slSavedWorld": "SELECIONAR MUNDO SALVO",
    "slNoBrowser": "Nenhum mundo salvo encontrado no navegador.",
    "slServerSettings": "CONFIGURAÇÕES DO SERVIDOR",
    "slLoadHost": "CARREGAR E HOSPEDAR",
    "slWorldLoading": "Carregando mundo...",
    "slWorldReadError": "⚠ Não foi possível ler os dados do mundo.",
    "slServerError": "⚠ Erro do servidor: ",
    "slSearchPh": "Buscar servidor...",
    "slConnecting": "Carregando servidores...",
    "slNoResponse": "⚠ Sem resposta do servidor.",
    "slNoServers": "Nenhum servidor ativo encontrado.",
    "slCreateServer": "⚙️ CRIAR SERVIDOR",
    "msTitle": "⚙ GERENCIAR SERVIDOR",
    "msTabPlayers": "👥 JOGADORES",
    "msTabAdmins": "🛡 ADMINS E BANIDOS",
    "msTabServer": "⚙ SERVIDOR",
    "msBtnManage": "🛡 GERENCIAR SERVIDOR",
    "msLblAdmins": "ADMINS",
    "msLblBanned": "BANIDOS",
    "msLblAccess": "Acesso",
    "msLblPvp": "PvP",
    "msLblCheats": "Trapaças",
    "msOptPublic": "🌐 Público",
    "msOptRegistered": "🔑 Apenas Registrados",
    "msOptPrivate": "🔒 Privado",
    "msBtnPromote": "Promover",
    "msBtnDemote": "Rebaixar",
    "msBtnKick": "Expulsar",
    "msBtnBan": "Banir",
    "msBtnUnban": "Desbanir",
    "msBtnShutdown": "🛑 DESLIGAR SERVIDOR",
    "msBtnClose": "← FECHAR",
    "msNoPlayers": "Nenhum jogador no servidor.",
    "msNoAdmins": "Nenhum admin.",
    "msNoBanned": "Nenhum jogador banido.",
    "msPvpOn": "ATIVADO",
    "msPvpOff": "DESATIVADO",
    "msCheatsOn": "ATIVADO",
    "msCheatsOff": "DESATIVADO",
    "hcModLabel": "MODO HARDCORE",
    "hcOn": "ATIVADO",
    "hcOff": "DESATIVADO",
    "hcWatchWorld": "Observar o Mundo",
    "hcMainMenu": "Voltar ao Menu Principal",
    "hcBlockedGeneric": "⛔ Comandos bloqueados no modo Hardcore.",
    "hcBlockedSpectator": "⛔ Bloqueado no modo Hardcore.",
    "specModeSet": "Modo de jogo definido para Espectador.",
    "hcWorldEnded": "💀 Este mundo Hardcore terminou. Você só pode observar.",
    "spStateRestored": "💾 Estado do mundo restaurado.",
    "spDeadTag": "☠ MORTO",
    "spDeadTooltip": "Abre no modo espectador",
    "myWorldsTitle": "MEUS MUNDOS",
    "newWorldBtn": "➕ CRIAR NOVO MUNDO",
    "noWorldsYet": "Ainda não há mundos salvos.",
    "noWorldsHint": "Crie ou jogue um novo mundo.",
    "editWorldName": "NOME DO MUNDO",
    "editWorldNamePh": "Nome do mundo...",
    "editWorldType": "TIPO DE MUNDO",
    "editGameMode": "MODO DE JOGO",
    "editCheats": "TRAPAÇAS",
    "saveBtn": "💾 SALVAR",
    "cancelBtn": "✖ CANCELAR",
    "wtNormal": "NORMAL",
    "wtFlat": "PLANO",
    "wtSmall": "PEQUENO",
    "gmSurvival": "SOBREVIVÊNCIA",
    "gmCreative": "CRIATIVO",
    "gmAdventure": "AVENTURA",
    "chOff": "DESATIVADO",
    "chOn": "ATIVADO",
    "f3Fps": "FPS",
    "f3Xyz": "XYZ",
    "f3Block": "Bloco",
    "f3Chunk": "Chunk",
    "f3Facing": "Direção",
    "f3Pitch": "Inclinação",
    "f3Biome": "Bioma",
    "f3Targeted": "Alvo",
    "f3World": "Mundo",
    "f3Seed": "Seed",
    "f3Mode": "Modo",
    "f3Flying": "Voando",
    "f3Grounded": "No chão",
    "f3Chunks": "Chunks",
    "controlsTabLabel": "Controles",
    "languageTabLabel": "Idioma"
  }
};

  // ── Aktif dili localStorage'dan oku (yoksa/geçersizse varsayılan EN) ─
  function readStoredLang(){
    try{
      var v = global.localStorage ? global.localStorage.getItem(STORAGE_KEY) : null;
      if(v && SUPPORTED.indexOf(v) !== -1) return v;
    }catch(e){ /* localStorage erişilemez (gizli sekme vb.) — sessizce yok say */ }
    return DEFAULT_LANG;
  }

  function storeLang(l){
    try{
      if(global.localStorage) global.localStorage.setItem(STORAGE_KEY, l);
    }catch(e){ /* kayıt başarısız olsa bile oyun akışını bozma */ }
  }

  // ── Güvenli erişim: dile ait key yoksa EN'e, o da yoksa key'in kendisine düş ──
  function get(lang, key){
    var d = LANG_DATA[lang] || LANG_DATA[DEFAULT_LANG];
    if(d && Object.prototype.hasOwnProperty.call(d, key)) return d[key];
    var fallback = LANG_DATA[DEFAULT_LANG];
    if(fallback && Object.prototype.hasOwnProperty.call(fallback, key)) return fallback[key];
    return key;
  }

  function buildLangProxy(lang){
    var base = LANG_DATA[lang] || {};
    var fallback = LANG_DATA[DEFAULT_LANG] || {};
    var merged = {};
    for(var k in fallback){ if(Object.prototype.hasOwnProperty.call(fallback,k)) merged[k]=fallback[k]; }
    for(var k2 in base){ if(Object.prototype.hasOwnProperty.call(base,k2)) merged[k2]=base[k2]; }
    return merged;
  }

  var LegendsLanguage = {
    STORAGE_KEY: STORAGE_KEY,
    DEFAULT_LANG: DEFAULT_LANG,
    SUPPORTED: SUPPORTED.slice(),
    raw: LANG_DATA,
    get: get,
    getDict: buildLangProxy,
    readStoredLang: readStoredLang,
    storeLang: storeLang
  };

  global.LegendsLanguage = LegendsLanguage;

  var proxiedLangData = {};
  SUPPORTED.forEach(function(l){ proxiedLangData[l] = buildLangProxy(l); });
  global.langData = proxiedLangData;

  global.currentLang = readStoredLang();

})(typeof window !== "undefined" ? window : this);
